In [2]:
from numpy import char
from datetime import date
import pandas as pd
import numpy as np
import time
pd.set_option('display.float_format', str)

In [3]:
import pandas as pd


# Lineitem

l_columnnames = ["L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX",
                "L_RETURNFLAG", "L_LINESTATUS", "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"]

for i in range(len(l_columnnames)):
    l_columnnames[i] = l_columnnames[i].lower()

l_data_types = {
    'l_orderkey': int,
    'l_partkey': int,
    'l_suppkey': int,
    'l_linenumber': int,
    'l_quantity': float,
    'l_extendedprice': float,
    'l_discount': float,
    'l_tax': float,
    'l_returnflag': str,
    'l_linestatus': str,
    'l_shipinstruct': str,
    'l_shipmode': str,
    'l_comment': str
}

l_parse_dates = ['l_shipdate', 'l_commitdate', 'l_receiptdate']

# Don't set indexes, as we can't access them with Pandas selection!
lineitem = pd.read_table("../data_storage/lineitem.tbl.csv", sep="|", names=l_columnnames, dtype=l_data_types, parse_dates=l_parse_dates)

# Order

o_columnnames = ["O_ORDERKEY", "O_CUSTKEY", "O_ORDERSTATUS", "O_TOTALPRICE", "O_ORDERDATE", "O_ORDERPRIORITY", "O_CLERK", "O_SHIPPRIORITY", "O_COMMENT"]

for i in range(len(o_columnnames)):
    o_columnnames[i] = o_columnnames[i].lower()
    
o_data_types = {
    'o_orderkey': int,
    'o_custkey': int,
    'o_orderstatus': str,
    'o_totalprice': float,
    'o_orderpriority': str,
    'o_clerk': str,
    'o_shippriority': int,
    'o_comment': str
}

o_parse_dates = ['o_orderdate']

# Don't set indexes, as we can't access them with Pandas selection!
orders = pd.read_table("../data_storage/orders.tbl.csv", sep="|", names=o_columnnames, dtype=o_data_types, parse_dates=o_parse_dates)

# Customer

c_columnnames = ["C_CUSTKEY", "C_NAME", "C_ADDRESS", "C_NATIONKEY", "C_PHONE", "C_ACCTBAL", "C_MKTSEGMENT", "C_COMMENT"]

for i in range(len(c_columnnames)):
    c_columnnames[i] = c_columnnames[i].lower()
    
c_data_types = {
    'c_custkey': int,
    'c_name': str,
    'c_address': str,
    'c_nationkey': int,
    'c_phone': str,
    'c_acctbal': float,
    'c_mktsegment': str,
    'c_comment': str
}

c_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
customer = pd.read_table("../data_storage/customer.tbl.csv", sep="|", names=c_columnnames, dtype=c_data_types, parse_dates=c_parse_dates)

# Part

p_columnnames = ["P_PARTKEY", "P_NAME", "P_MFGR", "P_BRAND", "P_TYPE", "P_SIZE", "P_CONTAINER", "P_RETAILPRICE", "P_COMMENT"]

for i in range(len(p_columnnames)):
    p_columnnames[i] = p_columnnames[i].lower()
    
p_data_types = {
    'p_partkey': int, 
    'p_name': str,
    'p_mfgr': str,
    'p_brand': str,
    'p_type': str,
    'p_size': int,
    'p_container': str,
    'p_retailprice': float,
    'p_comment': str
}

p_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
part = pd.read_table("../data_storage/part.tbl.csv", sep="|", names=p_columnnames, dtype=p_data_types, parse_dates=p_parse_dates)

# Nation

n_columnnames = ["N_NATIONKEY", "N_NAME", "N_REGIONKEY", "N_COMMENT"]

for i in range(len(n_columnnames)):
    n_columnnames[i] = n_columnnames[i].lower()
    
n_data_types = {
    'n_nationkey': int,
    'n_name': str,
    'n_regionkey': int,
    'n_comment': str,
}

n_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
nation = pd.read_table("../data_storage/nation.tbl.csv", sep="|", names=n_columnnames, dtype=n_data_types, parse_dates=n_parse_dates)

# Supplier

s_columnnames = ["S_SUPPKEY", "S_NAME", "S_ADDRESS", "S_NATIONKEY", "S_PHONE", "S_ACCTBAL", "S_COMMENT"]

for i in range(len(s_columnnames)):
    s_columnnames[i] = s_columnnames[i].lower()

s_data_types = {
    's_suppkey': int,
    's_name': str,
    's_address': str,
    's_nationkey': int,
    's_phone': str,
    's_acctbal': float,
    's_comment': str
}

s_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
# Don't set indexes, as we can't access them with Pandas selection!
supplier = pd.read_table("../data_storage/supplier.tbl.csv", sep="|", names=s_columnnames, dtype=s_data_types, parse_dates=s_parse_dates)

# Partsupp

ps_columnnames = ["PS_PARTKEY", "PS_SUPPKEY", "PS_AVAILQTY", "PS_SUPPLYCOST", "PS_COMMENT"]

for i in range(len(ps_columnnames)):
    ps_columnnames[i] = ps_columnnames[i].lower()

ps_data_types = {
    'ps_partkey': int,
    'ps_suppkey': int,
    'ps_availqty': int,
    'ps_supplycost': float,
    'ps_comment': str
}

ps_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
partsupp = pd.read_table("../data_storage/partsupp.tbl.csv", sep="|", names=ps_columnnames, dtype=ps_data_types, parse_dates=ps_parse_dates)

# Region

r_columnnames = ["R_REGIONKEY", "R_NAME", "R_COMMENT"]

for i in range(len(r_columnnames)):
    r_columnnames[i] = r_columnnames[i].lower()

r_data_types = {
    'r_regionkey': int,
    'r_name': str,
    'r_comment': str
}

r_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
region = pd.read_table("../data_storage/region.tbl.csv", sep="|", names=r_columnnames, dtype=r_data_types, parse_dates=r_parse_dates)

In [12]:
df_filter_1 = lineitem[['l_orderkey', 'l_partkey', 'l_suppkey', 'l_linenumber', 'l_quantity', 'l_extendedprice', 'l_discount', 'l_tax', 'l_returnflag', 'l_linestatus', 'l_shipdate', 'l_commitdate', 'l_receiptdate', 'l_shipinstruct', 'l_shipmode', 'l_comment']]
df_filter_2 = orders[['o_orderkey', 'o_custkey', 'o_orderstatus', 'o_totalprice', 'o_orderdate', 'o_orderpriority', 'o_clerk', 'o_shippriority', 'o_comment']]
df_filter_3 = lineitem[['l_orderkey', 'l_partkey', 'l_suppkey', 'l_linenumber', 'l_quantity', 'l_extendedprice', 'l_discount', 'l_tax', 'l_returnflag', 'l_linestatus', 'l_shipdate', 'l_commitdate', 'l_receiptdate', 'l_shipinstruct', 'l_shipmode', 'l_comment']]
df_group_1 = df_filter_3 \
    .groupby(['l_orderkey'], sort=False) \
    .agg(
        sum_l_quantity=("l_quantity", "sum"),
    )
df_group_1['suml_quantity'] = df_group_1.sum_l_quantity
df_group_1 = df_group_1[df_group_1.suml_quantity > 300]
df_group_2 = df_group_1 \
    .groupby(['l_orderkey'], sort=False) \
    .last()
df_group_2 = df_group_2.reset_index(level=0)
df_merge_1 = df_filter_2.merge(df_group_2, left_on=['o_orderkey'], right_on=['l_orderkey'], how="inner", sort=False)
df_merge_1 = df_merge_1[['o_custkey', 'o_orderkey', 'o_orderdate', 'o_totalprice', 'l_orderkey']]
df_filter_4 = customer[['c_name', 'c_custkey']]
df_merge_2 = df_merge_1.merge(df_filter_4, left_on=['o_custkey'], right_on=['c_custkey'], how="inner", sort=False)
df_merge_2 = df_merge_2[['c_name', 'o_custkey', 'o_orderkey', 'o_orderdate', 'o_totalprice', 'l_orderkey']]
df_merge_3 = df_filter_1.merge(df_merge_2, left_on=['l_orderkey'], right_on=['o_orderkey'], how="inner", sort=False)
df_merge_3 = df_merge_3[['c_name', 'o_orderkey', 'o_custkey', 'o_orderdate', 'o_totalprice', 'l_quantity']]
df_sort_1 = df_merge_3.sort_values(by=['c_name', 'o_orderkey'], ascending=[True, True])
df_sort_1 = df_sort_1[['c_name', 'o_orderkey', 'o_custkey', 'o_orderdate', 'o_totalprice', 'l_quantity']]
df_group_3 = df_sort_1 \
    .groupby(['c_name', 'o_orderkey'], sort=False) \
    .agg(
        o_custkey=("o_custkey", "last"),
        o_orderdate=("o_orderdate", "last"),
        o_totalprice=("o_totalprice", "last"),
        suml_quantity=("l_quantity", "sum"),
    )
df_group_3 = df_group_3[['o_custkey', 'o_orderdate', 'o_totalprice', 'suml_quantity']]
#return df_group_3

In [13]:
df_group_3

,,o_custkey,o_orderdate,o_totalprice,suml_quantity
c_name,o_orderkey,,,,
Customer#000003566,2329187,3566,1998-01-04,439803.36,304.0
Customer#000003680,3861123,3680,1998-07-03,433525.97,301.0
Customer#000010129,5849444,10129,1994-03-21,409129.85,309.0
Customer#000012251,735366,12251,1993-11-24,455107.26,309.0
Customer#000012599,4259524,12599,1998-02-12,415200.61,304.0
Customer#000013072,1481925,13072,1998-03-15,399195.47,301.0
Customer#000013940,2232932,13940,1997-04-13,522720.61,304.0
Customer#000015272,3883783,15272,1993-07-28,500241.33,302.0
Customer#000015619,3767271,15619,1996-08-07,480083.96,318.0
Customer#000015631,1845057,15631,1994-05-12,419879.59,302.0
Customer#000016384,502886,16384,1994-04-12,458378.92,312.0
Customer#000017746,6882,17746,1997-04-09,408446.93,303.0
Customer#000018188,3037414,18188,1995-01-25,443807.22,308.0
Customer#000024341,1474818,24341,1992-11-15,491348.26,302.0
Customer#000036619,4806726,36619,1995-01-17,446704.09,328.0
Customer#000037729,4134341,37729,1995-06-29,441082.97,309.0
Customer#000045538,4527553,45538,1994-05-22,436275.31,305.0
Customer#000046435,4745607,46435,1997-07-03,508047.99,309.0
Customer#000050008,2366755,50008,1996-12-09,483891.26,302.0
Customer#000053029,2662214,53029,1993-08-13,446144.49,302.0
Customer#000054602,5832321,54602,1997-02-09,471220.08,307.0
Customer#000064483,2745894,64483,1996-07-04,466991.35,304.0
Customer#000066098,5007490,66098,1992-08-07,453436.16,304.0
Customer#000066533,29158,66533,1995-10-21,443576.5,305.0
Customer#000066790,2199712,66790,1996-09-30,515531.82,327.0
Customer#000069904,1742403,69904,1996-10-19,408513.0,305.0
Customer#000077260,1436544,77260,1992-09-12,479499.43,307.0
Customer#000081581,4739650,81581,1995-11-04,435405.9,305.0
Customer#000082441,857959,82441,1994-02-07,382579.74,305.0
Customer#000088703,2995076,88703,1994-01-30,363812.12,302.0
Customer#000088876,983201,88876,1993-12-30,446717.46,304.0
Customer#000093392,5200102,93392,1997-01-22,425487.51,304.0
Customer#000096103,5984582,96103,1992-03-16,494398.79,312.0
Customer#000105260,5296167,105260,1996-09-06,469360.57,303.0
Customer#000105410,4478371,105410,1996-03-05,412754.51,302.0
Customer#000105995,2096705,105995,1994-07-03,469692.58,307.0
Customer#000107590,4267751,107590,1994-11-04,485141.38,301.0
Customer#000109379,5746311,109379,1996-10-10,478064.11,302.0
Customer#000112987,4439686,112987,1996-09-17,418161.49,305.0
Customer#000113131,967334,113131,1995-12-15,432957.75,301.0
Customer#000114586,551136,114586,1993-05-19,469605.59,308.0
Customer#000117076,4290656,117076,1997-02-05,449545.85,301.0
Customer#000117919,2869152,117919,1996-06-20,456815.92,317.0
Customer#000119989,1544643,119989,1997-09-20,434568.25,320.0
Customer#000120098,1971680,120098,1995-06-14,453451.23,308.0
Customer#000126865,4702759,126865,1994-11-07,447606.65,320.0
Customer#000128120,4722021,128120,1994-04-07,544089.09,323.0
Customer#000129379,4720454,129379,1997-06-07,448665.79,303.0
Customer#000136573,2761378,136573,1996-05-31,461282.73,301.0
Customer#000137446,5489475,137446,1997-05-23,487763.25,311.0
Customer#000141098,565574,141098,1995-09-24,430986.69,301.0
Customer#000141823,2806245,141823,1996-12-29,446269.12,310.0
Customer#000144617,3043270,144617,1997-02-12,530604.44,317.0
Customer#000146608,3342468,146608,1994-06-12,499794.58,303.0
Customer#000147197,1263015,147197,1997-02-02,467149.67,320.0
Customer#000148885,2942469,148885,1992-05-31,469630.44,313.0
Customer#000149842,5156581,149842,1994-05-30,411329.35,302.0