In [62]:
from numpy import char
from datetime import date
import pandas as pd
import numpy as np
import time
pd.set_option('display.float_format', str)

In [63]:
import pandas as pd


# Lineitem

l_columnnames = ["L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX",
                "L_RETURNFLAG", "L_LINESTATUS", "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"]

for i in range(len(l_columnnames)):
    l_columnnames[i] = l_columnnames[i].lower()

l_data_types = {
    'l_orderkey': int,
    'l_partkey': int,
    'l_suppkey': int,
    'l_linenumber': int,
    'l_quantity': float,
    'l_extendedprice': float,
    'l_discount': float,
    'l_tax': float,
    'l_returnflag': str,
    'l_linestatus': str,
    'l_shipinstruct': str,
    'l_shipmode': str,
    'l_comment': str
}

l_parse_dates = ['l_shipdate', 'l_commitdate', 'l_receiptdate']

# Don't set indexes, as we can't access them with Pandas selection!
lineitem = pd.read_table("../tpch-pgsql-master/data/load/lineitem.tbl.csv", sep="|", names=l_columnnames, dtype=l_data_types, parse_dates=l_parse_dates)

# Order

o_columnnames = ["O_ORDERKEY", "O_CUSTKEY", "O_ORDERSTATUS", "O_TOTALPRICE", "O_ORDERDATE", "O_ORDERPRIORITY", "O_CLERK", "O_SHIPPRIORITY", "O_COMMENT"]

for i in range(len(o_columnnames)):
    o_columnnames[i] = o_columnnames[i].lower()
    
o_data_types = {
    'o_orderkey': int,
    'o_custkey': int,
    'o_orderstatus': str,
    'o_totalprice': float,
    'o_orderpriority': str,
    'o_clerk': str,
    'o_shippriority': int,
    'o_comment': str
}

o_parse_dates = ['o_orderdate']

# Don't set indexes, as we can't access them with Pandas selection!
orders = pd.read_table("../tpch-pgsql-master/data/load/orders.tbl.csv", sep="|", names=o_columnnames, dtype=o_data_types, parse_dates=o_parse_dates)

# Customer

c_columnnames = ["C_CUSTKEY", "C_NAME", "C_ADDRESS", "C_NATIONKEY", "C_PHONE", "C_ACCTBAL", "C_MKTSEGMENT", "C_COMMENT"]

for i in range(len(c_columnnames)):
    c_columnnames[i] = c_columnnames[i].lower()
    
c_data_types = {
    'c_custkey': int,
    'c_name': str,
    'c_address': str,
    'c_nationkey': int,
    'c_phone': str,
    'c_acctbal': float,
    'c_mktsegment': str,
    'c_comment': str
}

c_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
customer = pd.read_table("../tpch-pgsql-master/data/load/customer.tbl.csv", sep="|", names=c_columnnames, dtype=c_data_types, parse_dates=c_parse_dates)

# Part

p_columnnames = ["P_PARTKEY", "P_NAME", "P_MFGR", "P_BRAND", "P_TYPE", "P_SIZE", "P_CONTAINER", "P_RETAILPRICE", "P_COMMENT"]

for i in range(len(p_columnnames)):
    p_columnnames[i] = p_columnnames[i].lower()
    
p_data_types = {
    'p_partkey': int, 
    'p_name': str,
    'p_mfgr': str,
    'p_brand': str,
    'p_type': str,
    'p_size': int,
    'p_container': str,
    'p_retailprice': float,
    'p_comment': str
}

p_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
part = pd.read_table("../tpch-pgsql-master/data/load/part.tbl.csv", sep="|", names=p_columnnames, dtype=p_data_types, parse_dates=p_parse_dates)

# Nation

n_columnnames = ["N_NATIONKEY", "N_NAME", "N_REGIONKEY", "N_COMMENT"]

for i in range(len(n_columnnames)):
    n_columnnames[i] = n_columnnames[i].lower()
    
n_data_types = {
    'n_nationkey': int,
    'n_name': str,
    'n_regionkey': int,
    'n_comment': str,
}

n_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
nation = pd.read_table("../tpch-pgsql-master/data/load/nation.tbl.csv", sep="|", names=n_columnnames, dtype=n_data_types, parse_dates=n_parse_dates)

# Supplier

s_columnnames = ["S_SUPPKEY", "S_NAME", "S_ADDRESS", "S_NATIONKEY", "S_PHONE", "S_ACCTBAL", "S_COMMENT"]

for i in range(len(s_columnnames)):
    s_columnnames[i] = s_columnnames[i].lower()

s_data_types = {
    's_suppkey': int,
    's_name': str,
    's_address': str,
    's_nationkey': int,
    's_phone': str,
    's_acctbal': float,
    's_comment': str
}

s_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
# Don't set indexes, as we can't access them with Pandas selection!
supplier = pd.read_table("../tpch-pgsql-master/data/load/supplier.tbl.csv", sep="|", names=s_columnnames, dtype=s_data_types, parse_dates=s_parse_dates)

# Partsupp

ps_columnnames = ["PS_PARTKEY", "PS_SUPPKEY", "PS_AVAILQTY", "PS_SUPPLYCOST", "PS_COMMENT"]

for i in range(len(ps_columnnames)):
    ps_columnnames[i] = ps_columnnames[i].lower()

ps_data_types = {
    'ps_partkey': int,
    'ps_suppkey': int,
    'ps_availqty': int,
    'ps_supplycost': float,
    'ps_comment': str
}

ps_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
partsupp = pd.read_table("../tpch-pgsql-master/data/load/partsupp.tbl.csv", sep="|", names=ps_columnnames, dtype=ps_data_types, parse_dates=ps_parse_dates)

# Region

r_columnnames = ["R_REGIONKEY", "R_NAME", "R_COMMENT"]

for i in range(len(r_columnnames)):
    r_columnnames[i] = r_columnnames[i].lower()

r_data_types = {
    'r_regionkey': int,
    'r_name': str,
    'r_comment': str
}

r_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
region = pd.read_table("../tpch-pgsql-master/data/load/region.tbl.csv", sep="|", names=r_columnnames, dtype=r_data_types, parse_dates=r_parse_dates)

#### Notes

- Should the df_filter_1 be increasing for the non-subplan from the point the subplan leaves off

In [84]:
df_filter_1 = region[region.r_name == 'EUROPE']
df_filter_1 = df_filter_1[['r_regionkey', 'r_name', 'r_comment']]
df_filter_2 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_availqty', 'ps_supplycost', 'ps_comment']]
#df_filter_2 = df_filter_2[df_filter_2.ps_partkey == part.p_partkey]
df_filter_3 = supplier[['s_suppkey', 's_name', 's_address', 's_nationkey', 's_phone', 's_acctbal', 's_comment']]
df_merge_1 = df_filter_2.merge(df_filter_3, left_on="ps_suppkey", right_on="s_suppkey")
df_merge_1 = df_merge_1[['ps_supplycost', 's_nationkey']]
df_filter_4 = nation[['n_nationkey', 'n_name', 'n_regionkey', 'n_comment']]
df_merge_2 = df_merge_1.merge(df_filter_4, left_on="s_nationkey", right_on="n_nationkey")
df_merge_2 = df_merge_2[['ps_supplycost', 'n_regionkey']]
df_merge_3 = df_filter_1.merge(df_merge_2, left_on="r_regionkey", right_on="n_regionkey")
df_merge_3 = df_merge_3[['ps_supplycost']]
df_aggr_1 = pd.DataFrame()
df_aggr_1['minps_supplycost'] = [(df_merge_3.ps_supplycost).min()]
df_aggr_1 = df_aggr_1[['minps_supplycost']]
#SubPlan 1 = df_aggr_1['minps_supplycost'][0]

df_filter_5 = part[['p_partkey', 'p_name', 'p_mfgr', 'p_brand', 'p_type', 'p_size', 'p_container', 'p_retailprice', 'p_comment']]
df_filter_6 = region[region.r_name == 'EUROPE']
df_filter_6 = df_filter_6[['r_regionkey', 'r_name', 'r_comment']]
df_filter_7 = nation[['n_nationkey', 'n_name', 'n_regionkey', 'n_comment']]
df_merge_4 = df_filter_6.merge(df_filter_7, left_on="r_regionkey", right_on="n_regionkey")
df_merge_4 = df_merge_4[['n_name', 'n_nationkey']]
df_filter_8 = supplier[['s_suppkey', 's_name', 's_address', 's_nationkey', 's_phone', 's_acctbal', 's_comment']]
df_merge_5 = df_merge_4.merge(df_filter_8, left_on="n_nationkey", right_on="s_nationkey")
df_merge_5 = df_merge_5[['s_acctbal', 's_name', 's_address', 's_phone', 's_comment', 's_suppkey', 'n_name']]
df_filter_9 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_availqty', 'ps_supplycost', 'ps_comment']]
df_merge_6 = df_merge_5.merge(df_filter_9, left_on="s_suppkey", right_on="ps_suppkey")
df_merge_6 = df_merge_6[['s_acctbal', 's_name', 's_address', 's_phone', 's_comment', 'ps_partkey', 'ps_supplycost', 'n_name']]
df_sort_1 = df_merge_6.sort_values(by=['ps_partkey'], ascending=[True])
df_sort_1 = df_sort_1[['s_acctbal', 's_name', 's_address', 's_phone', 's_comment', 'ps_partkey', 'ps_supplycost', 'n_name']]
df_merge_7 = df_filter_5.merge(df_sort_1, left_on="p_partkey", right_on="ps_partkey")
df_merge_7 = df_merge_7[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
df_sort_2 = df_merge_7.sort_values(by=['s_acctbal', 'n_name', 's_name', 'p_partkey'], ascending=[False, True, True, True])
df_sort_2 = df_sort_2[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
df_limit_1 = df_sort_2[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
#df_limit_1 = df_limit_1.head(100)

In [85]:
df_limit_1

,s_acctbal,s_name,n_name,p_partkey,p_mfgr,s_address,s_phone,s_comment
1115,9990.05,Supplier#000008890,ROMANIA,1389,Manufacturer#1,6lmM3OrUukwhKXY0zqypO2qEsgj,29-208-398-4306,ts. unusual deposits haggle furiously along th...
3102,9990.05,Supplier#000008890,ROMANIA,3889,Manufacturer#3,6lmM3OrUukwhKXY0zqypO2qEsgj,29-208-398-4306,ts. unusual deposits haggle furiously along th...
5089,9990.05,Supplier#000008890,ROMANIA,6389,Manufacturer#5,6lmM3OrUukwhKXY0zqypO2qEsgj,29-208-398-4306,ts. unusual deposits haggle furiously along th...
7076,9990.05,Supplier#000008890,ROMANIA,8889,Manufacturer#3,6lmM3OrUukwhKXY0zqypO2qEsgj,29-208-398-4306,ts. unusual deposits haggle furiously along th...
9062,9990.05,Supplier#000008890,ROMANIA,11386,Manufacturer#2,6lmM3OrUukwhKXY0zqypO2qEsgj,29-208-398-4306,ts. unusual deposits haggle furiously along th...
...,...,...,...,...,...,...,...,...
149390,-993.76,Supplier#000007956,FRANCE,187955,Manufacturer#4,vmAYh95Lr3f2kKHl6kRX2G7,16-947-231-8954,ly among the blithely regular requests. ironic
151326,-993.76,Supplier#000007956,FRANCE,190398,Manufacturer#3,vmAYh95Lr3f2kKHl6kRX2G7,16-947-231-8954,ly among the blithely regular requests. ironic
153329,-993.76,Supplier#000007956,FRANCE,192917,Manufacturer#4,vmAYh95Lr3f2kKHl6kRX2G7,16-947-231-8954,ly among the blithely regular requests. ironic
155332,-993.76,Supplier#000007956,FRANCE,195436,Manufacturer#5,vmAYh95Lr3f2kKHl6kRX2G7,16-947-231-8954,ly among the blithely regular requests. ironic
157337,-993.76,Supplier#000007956,FRANCE,197955,Manufacturer#4,vmAYh95Lr3f2kKHl6kRX2G7,16-947-231-8954,ly among the blithely regular requests. ironic