In [1]:
from numpy import char
from datetime import date
import pandas as pd
import numpy as np
import time
pd.set_option('display.float_format', str)

In [2]:
import pandas as pd


# Lineitem

l_columnnames = ["L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX",
                "L_RETURNFLAG", "L_LINESTATUS", "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"]

for i in range(len(l_columnnames)):
    l_columnnames[i] = l_columnnames[i].lower()

l_data_types = {
    'l_orderkey': int,
    'l_partkey': int,
    'l_suppkey': int,
    'l_linenumber': int,
    'l_quantity': float,
    'l_extendedprice': float,
    'l_discount': float,
    'l_tax': float,
    'l_returnflag': str,
    'l_linestatus': str,
    'l_shipinstruct': str,
    'l_shipmode': str,
    'l_comment': str
}

l_parse_dates = ['l_shipdate', 'l_commitdate', 'l_receiptdate']

# Don't set indexes, as we can't access them with Pandas selection!
lineitem = pd.read_table("../data_storage/lineitem.tbl.csv", sep="|", names=l_columnnames, dtype=l_data_types, parse_dates=l_parse_dates)

# Order

o_columnnames = ["O_ORDERKEY", "O_CUSTKEY", "O_ORDERSTATUS", "O_TOTALPRICE", "O_ORDERDATE", "O_ORDERPRIORITY", "O_CLERK", "O_SHIPPRIORITY", "O_COMMENT"]

for i in range(len(o_columnnames)):
    o_columnnames[i] = o_columnnames[i].lower()
    
o_data_types = {
    'o_orderkey': int,
    'o_custkey': int,
    'o_orderstatus': str,
    'o_totalprice': float,
    'o_orderpriority': str,
    'o_clerk': str,
    'o_shippriority': int,
    'o_comment': str
}

o_parse_dates = ['o_orderdate']

# Don't set indexes, as we can't access them with Pandas selection!
orders = pd.read_table("../data_storage/orders.tbl.csv", sep="|", names=o_columnnames, dtype=o_data_types, parse_dates=o_parse_dates)

# Customer

c_columnnames = ["C_CUSTKEY", "C_NAME", "C_ADDRESS", "C_NATIONKEY", "C_PHONE", "C_ACCTBAL", "C_MKTSEGMENT", "C_COMMENT"]

for i in range(len(c_columnnames)):
    c_columnnames[i] = c_columnnames[i].lower()
    
c_data_types = {
    'c_custkey': int,
    'c_name': str,
    'c_address': str,
    'c_nationkey': int,
    'c_phone': str,
    'c_acctbal': float,
    'c_mktsegment': str,
    'c_comment': str
}

c_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
customer = pd.read_table("../data_storage/customer.tbl.csv", sep="|", names=c_columnnames, dtype=c_data_types, parse_dates=c_parse_dates)

# Part

p_columnnames = ["P_PARTKEY", "P_NAME", "P_MFGR", "P_BRAND", "P_TYPE", "P_SIZE", "P_CONTAINER", "P_RETAILPRICE", "P_COMMENT"]

for i in range(len(p_columnnames)):
    p_columnnames[i] = p_columnnames[i].lower()
    
p_data_types = {
    'p_partkey': int, 
    'p_name': str,
    'p_mfgr': str,
    'p_brand': str,
    'p_type': str,
    'p_size': int,
    'p_container': str,
    'p_retailprice': float,
    'p_comment': str
}

p_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
part = pd.read_table("../data_storage/part.tbl.csv", sep="|", names=p_columnnames, dtype=p_data_types, parse_dates=p_parse_dates)

# Nation

n_columnnames = ["N_NATIONKEY", "N_NAME", "N_REGIONKEY", "N_COMMENT"]

for i in range(len(n_columnnames)):
    n_columnnames[i] = n_columnnames[i].lower()
    
n_data_types = {
    'n_nationkey': int,
    'n_name': str,
    'n_regionkey': int,
    'n_comment': str,
}

n_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
nation = pd.read_table("../data_storage/nation.tbl.csv", sep="|", names=n_columnnames, dtype=n_data_types, parse_dates=n_parse_dates)

# Supplier

s_columnnames = ["S_SUPPKEY", "S_NAME", "S_ADDRESS", "S_NATIONKEY", "S_PHONE", "S_ACCTBAL", "S_COMMENT"]

for i in range(len(s_columnnames)):
    s_columnnames[i] = s_columnnames[i].lower()

s_data_types = {
    's_suppkey': int,
    's_name': str,
    's_address': str,
    's_nationkey': int,
    's_phone': str,
    's_acctbal': float,
    's_comment': str
}

s_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
# Don't set indexes, as we can't access them with Pandas selection!
supplier = pd.read_table("../data_storage/supplier.tbl.csv", sep="|", names=s_columnnames, dtype=s_data_types, parse_dates=s_parse_dates)

# Partsupp

ps_columnnames = ["PS_PARTKEY", "PS_SUPPKEY", "PS_AVAILQTY", "PS_SUPPLYCOST", "PS_COMMENT"]

for i in range(len(ps_columnnames)):
    ps_columnnames[i] = ps_columnnames[i].lower()

ps_data_types = {
    'ps_partkey': int,
    'ps_suppkey': int,
    'ps_availqty': int,
    'ps_supplycost': float,
    'ps_comment': str
}

ps_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
partsupp = pd.read_table("../data_storage/partsupp.tbl.csv", sep="|", names=ps_columnnames, dtype=ps_data_types, parse_dates=ps_parse_dates)

# Region

r_columnnames = ["R_REGIONKEY", "R_NAME", "R_COMMENT"]

for i in range(len(r_columnnames)):
    r_columnnames[i] = r_columnnames[i].lower()

r_data_types = {
    'r_regionkey': int,
    'r_name': str,
    'r_comment': str
}

r_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
region = pd.read_table("../data_storage/region.tbl.csv", sep="|", names=r_columnnames, dtype=r_data_types, parse_dates=r_parse_dates)

In [3]:
df_filter_1 = lineitem[(lineitem.l_receiptdate > lineitem.l_commitdate)]
df_filter_1 = df_filter_1[['l_suppkey', 'l_orderkey', 'l_receiptdate', 'l_commitdate']]
df_filter_2 = orders[(orders.o_orderstatus == 'F') & (~orders.o_orderstatus.isnull())]
df_filter_2 = df_filter_2[['o_orderkey', 'o_orderstatus']]
df_merge_1 = df_filter_1.merge(df_filter_2, left_on=['l_orderkey'], right_on=['o_orderkey'], how="inner", sort=False)
df_filter_3 = supplier[['s_suppkey', 's_nationkey', 's_name']]
df_filter_4 = nation[(nation.n_name == 'SAUDI ARABIA') & (~nation.n_name.isnull())]
df_filter_4 = df_filter_4[['n_nationkey', 'n_name']]
df_merge_2 = df_filter_3.merge(df_filter_4, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_merge_3 = df_merge_1.merge(df_merge_2, left_on=['l_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_5 = lineitem[['l_orderkey', 'l_suppkey']]

# Semi join
# l_orderkey = l_orderkey AND l_suppkey != l_suppkey
#df_merge_4 = df_merge_3.merge(df_filter_5[['l_orderkey', 'l_suppkey']], how="inner", left_on=['l_orderkey', 'l_suppkey'], right_on=['l_orderkey', 'l_suppkey'], sort=False)
inner_cond = df_merge_3.merge(df_filter_5, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_merge_4 = df_merge_3[df_merge_3.l_orderkey.isin(inner_cond)]

df_filter_6 = lineitem[(lineitem.l_receiptdate > lineitem.l_commitdate)]
df_filter_6 = df_filter_6[['l_orderkey', 'l_suppkey', 'l_receiptdate', 'l_commitdate']]

# Anti join
# l_orderkey = l_orderkey AND l_suppkey != l_suppkey
#df_merge_5 = df_merge_4.merge(df_filter_6, left_on=['l_orderkey', 'l_suppkey'], right_on=['l_orderkey', 'l_suppkey'], how="outer", indicator=True, sort=False)
#df_merge_5 = df_merge_5[df_merge_5._merge == "left_only"]
inner_cond = df_merge_4.merge(df_filter_6, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_merge_5 = df_merge_4.merge(inner_cond, left_on=['l_orderkey'], right_on=['l_orderkey'], how="outer", indicator=True, sort=False)
df_merge_5 = df_merge_5[df_merge_5._merge == "left_only"]

df_group_1 = df_merge_5 \
    .groupby(['s_name'], sort=False) \
    .agg(
        numwait=("s_name", "count"),
    )
df_group_1 = df_group_1[['numwait']]
df_sort_1 = df_group_1.sort_values(by=['numwait', 's_name'], ascending=[False, True])
df_limit_1 = df_sort_1.head(100)
#return df_limit_1

In [4]:
df_limit_1

                    numwait
s_name
Supplier#000002829       20
Supplier#000005808       18
Supplier#000000262       17
Supplier#000000496       17
Supplier#000002160       17
...                     ...
Supplier#000001916       12
Supplier#000001925       12
Supplier#000002039       12
Supplier#000002357       12
Supplier#000002483       12

[100 rows x 1 columns]

In [5]:
df_filter_1 = lineitem[(lineitem.l_receiptdate > lineitem.l_commitdate)]
df_filter_1 = df_filter_1[['l_suppkey', 'l_orderkey', 'l_receiptdate', 'l_commitdate']]
df_filter_2 = orders[(orders.o_orderstatus == 'F') & (~orders.o_orderstatus.isnull())]
df_filter_2 = df_filter_2[['o_orderkey', 'o_orderstatus']]
df_merge_1 = df_filter_1.merge(df_filter_2, left_on=['l_orderkey'], right_on=['o_orderkey'], how="inner", sort=False)
df_filter_3 = supplier[['s_suppkey', 's_nationkey', 's_name']]
df_filter_4 = nation[(nation.n_name == 'SAUDI ARABIA') & (~nation.n_name.isnull())]
df_filter_4 = df_filter_4[['n_nationkey', 'n_name']]
df_merge_2 = df_filter_3.merge(df_filter_4, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_merge_3 = df_merge_1.merge(df_merge_2, left_on=['l_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_5 = lineitem[['l_orderkey', 'l_suppkey']]
inner_cond = df_merge_3.merge(df_filter_5, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_merge_4 = df_merge_3[df_merge_3.l_orderkey.isin(inner_cond)]
df_filter_6 = lineitem[(lineitem.l_receiptdate > lineitem.l_commitdate)]
df_filter_6 = df_filter_6[['l_orderkey', 'l_suppkey', 'l_receiptdate', 'l_commitdate']]
inner_cond = df_merge_4.merge(df_filter_6, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_merge_5 = df_merge_4.merge(inner_cond, left_on=['l_orderkey'], right_on=['l_orderkey'], how="outer", indicator=True, sort=False)
df_merge_5 = df_merge_5[df_merge_5._merge == "left_only"]
df_group_1 = df_merge_5 \
    .groupby(['s_name'], sort=False) \
    .agg(
        numwait=("s_name", "count"),
    )
df_group_1 = df_group_1[['numwait']]
df_sort_1 = df_group_1.sort_values(by=['numwait', 's_name'], ascending=[False, True])
df_limit_1 = df_sort_1.head(100)
#return df_limit_1

In [6]:
df_limit_1

                    numwait
s_name
Supplier#000002829       20
Supplier#000005808       18
Supplier#000000262       17
Supplier#000000496       17
Supplier#000002160       17
...                     ...
Supplier#000001916       12
Supplier#000001925       12
Supplier#000002039       12
Supplier#000002357       12
Supplier#000002483       12

[100 rows x 1 columns]

In [7]:
df_filter_1 = lineitem[(lineitem.l_receiptdate > lineitem.l_commitdate)]
df_filter_1 = df_filter_1[['l_suppkey', 'l_orderkey', 'l_receiptdate', 'l_commitdate']]
df_filter_2 = orders[(orders.o_orderstatus == 'F') & (~orders.o_orderstatus.isnull())]
df_filter_2 = df_filter_2[['o_orderkey', 'o_orderstatus']]
df_merge_1 = df_filter_1.merge(df_filter_2, left_on=['l_orderkey'], right_on=['o_orderkey'], how="inner", sort=False)
df_filter_3 = supplier[['s_suppkey', 's_nationkey', 's_name']]
df_filter_4 = nation[(nation.n_name == 'SAUDI ARABIA') & (~nation.n_name.isnull())]
df_filter_4 = df_filter_4[['n_nationkey', 'n_name']]
df_merge_2 = df_filter_3.merge(df_filter_4, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_merge_3 = df_merge_1.merge(df_merge_2, left_on=['l_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_5 = lineitem[['l_orderkey', 'l_suppkey']]

print(f"df_merge_3: {len(df_merge_3)}")
print(f"df_filter_5: {len(df_filter_5)}")

inner_cond = df_merge_3.merge(df_filter_5, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_merge_4 = df_merge_3[df_merge_3.l_orderkey.isin(inner_cond)]
print(len(df_merge_4))
df_filter_6 = lineitem[(lineitem.l_receiptdate > lineitem.l_commitdate)]
df_filter_6 = df_filter_6[['l_orderkey', 'l_suppkey', 'l_receiptdate', 'l_commitdate']]

print(f"df_merge_4: {len(df_merge_4)}")
print(f"df_filter_6: {len(df_filter_6)}")

inner_cond = df_merge_4.merge(df_filter_6, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_merge_5 = df_merge_4.merge(inner_cond, left_on=['l_orderkey'], right_on=['l_orderkey'], how="outer", indicator=True, sort=False)
df_merge_5 = df_merge_5[df_merge_5._merge == "left_only"]

print(len(df_merge_5))

df_group_1 = df_merge_5 \
    .groupby(['s_name'], sort=False, as_index=False) \
    .agg(
        numwait=("s_name", "count"),
    )
df_group_1 = df_group_1[['numwait', 's_name']]
df_sort_1 = df_group_1.sort_values(by=['numwait', 's_name'], ascending=[False, True])
df_limit_1 = df_sort_1.head(100)

df_merge_3: 75871
df_filter_5: 6001215
73089
df_merge_4: 73089
df_filter_6: 3793296
4141

In [8]:
df_limit_1

     numwait              s_name
155       20  Supplier#000002829
248       18  Supplier#000005808
371       17  Supplier#000000262
58        17  Supplier#000000496
49        17  Supplier#000002160
..       ...                 ...
11        12  Supplier#000001916
283       12  Supplier#000001925
87        12  Supplier#000002039
20        12  Supplier#000002357
352       12  Supplier#000002483

[100 rows x 2 columns]

In [9]:
df_scan_1 = nation[(nation.n_name == 'SAUDI ARABIA')]
df_scan_1 = df_scan_1[['n_nationkey', 'n_name']]
df_scan_2 = supplier[['s_suppkey', 's_name', 's_nationkey']]
df_join_1 = df_scan_1.merge(df_scan_2, left_on=['n_nationkey'], right_on=['s_nationkey'], how='inner', sort=False)
df_scan_3 = lineitem[['l_orderkey', 'l_suppkey', 'l_commitdate', 'l_receiptdate']]
df_filter_1 = df_scan_3[(df_scan_3.l_receiptdate > df_scan_3.l_commitdate)]
df_join_2 = df_join_1.merge(df_filter_1, left_on=['s_suppkey'], right_on=['l_suppkey'], how='inner', sort=False)
df_scan_4 = orders[(orders.o_orderstatus == 'F')]
df_scan_4 = df_scan_4[['o_orderkey', 'o_orderstatus']]
df_join_3 = df_join_2.merge(df_scan_4, left_on=['l_orderkey'], right_on=['o_orderkey'], how='inner', sort=False)
df_scan_5 = lineitem[['l_orderkey', 'l_suppkey', 'l_commitdate', 'l_receiptdate']]
df_filter_2 = df_scan_5[(df_scan_5.l_receiptdate > df_scan_5.l_commitdate)]

print(f"df_join_3: {len(df_join_3)}")
print(f"df_filter_2: {len(df_filter_2)}")

inner_cond = df_join_3.merge(df_filter_2, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_join_4 = df_join_3.merge(inner_cond, left_on=['l_orderkey'], right_on=['l_orderkey'], how="outer", indicator=True, sort=False)
df_join_4 = df_join_4[df_join_4._merge == "left_only"]


print(len(df_join_4))

# Bad here
# df_join_4 = df_join_3.merge(df_filter_2, how='cross', sort=False)
# df_join_4 = df_join_4[(df_join_4.l_suppkey != df_join_4.l_suppkey)]
df_scan_6 = lineitem[['l_orderkey', 'l_suppkey']]

print(f"df_join_4: {len(df_join_4)}")
print(f"df_scan_6: {len(df_scan_6)}")

inner_cond = df_join_4.merge(df_scan_6, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[inner_cond.l_suppkey_x != inner_cond.l_suppkey_y]['l_orderkey']
df_join_5 = df_join_4[df_join_4.l_orderkey.isin(inner_cond)]

print(len(df_join_5))

# Bad here
#df_join_5 = df_join_4.merge(df_scan_6, how='cross', sort=False)
#df_join_5 = df_join_5[(df_join_5.l_suppkey != df_join_5.l_suppkey)]
df_group_1 = df_join_5 \
    .groupby(['s_name'], sort=False, as_index=False) \
    .agg(
        count=('s_nationkey', 'count'),
    )
df_sort_1 = df_group_1.sort_values(
    by=['count', 's_name'],
    ascending=[False, True]
)
df_output_1 = df_sort_1.rename(columns={'count': 'numwait'})
df_output_1 = df_output_1[['s_name', 'numwait']]

df_join_3: 75871
df_filter_2: 3793296
6923
df_join_4: 6923
df_scan_6: 6001215
4141

In [10]:
df_output_1

                 s_name  numwait
121  Supplier#000002829       20
231  Supplier#000005808       18
5    Supplier#000000262       17
17   Supplier#000000496       17
96   Supplier#000002160       17
..                  ...      ...
238  Supplier#000005998        4
398  Supplier#000009721        4
272  Supplier#000006684        3
323  Supplier#000007656        3
340  Supplier#000008136        3

[411 rows x 2 columns]

In [11]:
df_scan_1 = nation[(nation.n_name == 'SAUDI ARABIA')]
df_scan_1 = df_scan_1[['n_nationkey', 'n_name']]
df_scan_2 = supplier[['s_suppkey', 's_name', 's_nationkey']]
df_join_1 = df_scan_1.merge(df_scan_2, left_on=['n_nationkey'], right_on=['s_nationkey'], how='inner', sort=False)
print(f"df_join_1: {len(df_join_1)}")
df_scan_3 = lineitem[['l_orderkey', 'l_suppkey', 'l_commitdate', 'l_receiptdate']]
df_filter_1 = df_scan_3[(df_scan_3.l_receiptdate > df_scan_3.l_commitdate)]
df_join_2 = df_join_1.merge(df_filter_1, left_on=['s_suppkey'], right_on=['l_suppkey'], how='inner', sort=False)
print(f"df_join_2: {len(df_join_2)}")
df_scan_4 = orders[(orders.o_orderstatus == 'F')]
df_scan_4 = df_scan_4[['o_orderkey', 'o_orderstatus']]
df_join_3 = df_join_2.merge(df_scan_4, left_on=['l_orderkey'], right_on=['o_orderkey'], how='inner', sort=False)
print(f"df_join_3: {len(df_join_3)}")
df_scan_5 = lineitem[['l_orderkey', 'l_suppkey', 'l_commitdate', 'l_receiptdate']]
df_filter_2 = df_scan_5[(df_scan_5.l_receiptdate > df_scan_5.l_commitdate)]
inner_cond = df_join_3.merge(df_filter_2, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[(inner_cond.l_suppkey_x != inner_cond.l_suppkey_y)]['l_orderkey']
df_join_4 = df_join_3.merge(inner_cond, left_on=['l_orderkey'], right_on=['l_orderkey'], how='outer', sort=False, indicator=True)
df_join_4 = df_join_4[df_join_4._merge == 'left_only'].drop('_merge', axis = 1)
print(f"df_join_4: {len(df_join_4)}")

df_join_1: 411
df_join_2: 156739
df_join_3: 75871
df_join_4: 6923

In [12]:
print(f"inner_cond: {len(inner_cond)}")
inner_cond

inner_cond: 190928

0           10149
2           10149
3           10149
4           10149
6           30374
           ...
266806    5917315
266807    5920835
266808    5920835
266811    5958692
266812    5958692
Name: l_orderkey, Length: 190928, dtype: int64

In [13]:
df_scan_6 = lineitem[['l_orderkey', 'l_suppkey']]
inner_cond = df_join_4.merge(df_scan_6, left_on='l_orderkey', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[(inner_cond.l_suppkey_x != inner_cond.l_suppkey_y)]
df_join_5 = df_join_4[df_join_4['l_orderkey'].isin(inner_cond['l_orderkey'])]
print(f"df_join_5: {len(df_join_5)}")
df_group_1 = df_join_5 \
    .groupby(['s_name'], sort=False, as_index=False) \
    .agg(
        count=('s_nationkey', 'count'),
    )
df_sort_1 = df_group_1.sort_values(
    by=['count', 's_name'],
    ascending=[False, True]
)
df_output_1 = df_sort_1.rename(columns={'count': 'numwait'})
df_output_1 = df_output_1[['s_name', 'numwait']]
print(f"df_output_1: {len(df_output_1)}")

df_join_5: 4141
df_output_1: 411

In [14]:
df_output_1

                 s_name  numwait
121  Supplier#000002829       20
231  Supplier#000005808       18
5    Supplier#000000262       17
17   Supplier#000000496       17
96   Supplier#000002160       17
..                  ...      ...
238  Supplier#000005998        4
398  Supplier#000009721        4
272  Supplier#000006684        3
323  Supplier#000007656        3
340  Supplier#000008136        3

[411 rows x 2 columns]

In [15]:
df_scan_1 = nation[(nation.n_name == 'SAUDI ARABIA')]
df_scan_1 = df_scan_1[['n_nationkey', 'n_name']]
df_scan_2 = supplier[['s_suppkey', 's_name', 's_nationkey']]
df_join_1 = df_scan_1.merge(df_scan_2, left_on=['n_nationkey'], right_on=['s_nationkey'], how='inner', sort=False)
df_scan_3 = lineitem[['l_orderkey', 'l_suppkey', 'l_commitdate', 'l_receiptdate']]
df_scan_3 = df_scan_3.rename(columns={'l_orderkey': 'l_orderkey_x', 'l_suppkey': 'l_suppkey_x'})
df_filter_1 = df_scan_3[(df_scan_3.l_receiptdate > df_scan_3.l_commitdate)]
df_join_2 = df_join_1.merge(df_filter_1, left_on=['s_suppkey'], right_on=['l_suppkey_x'], how='inner', sort=False)
df_scan_4 = orders[(orders.o_orderstatus == 'F')]
df_scan_4 = df_scan_4[['o_orderkey', 'o_orderstatus']]
df_join_3 = df_join_2.merge(df_scan_4, left_on=['l_orderkey_x'], right_on=['o_orderkey'], how='inner', sort=False)
df_scan_5 = lineitem[['l_orderkey', 'l_suppkey', 'l_commitdate', 'l_receiptdate']]
df_scan_5 = df_scan_5.rename(columns={'l_orderkey': 'l_orderkey_y', 'l_suppkey': 'l_suppkey_y'})
df_filter_2 = df_scan_5[(df_scan_5.l_receiptdate > df_scan_5.l_commitdate)]
inner_cond = df_join_3.merge(df_filter_2, left_on='l_orderkey_x', right_on='l_orderkey_y', how='inner', sort=False)
inner_cond = inner_cond[(inner_cond.l_suppkey_y != inner_cond.l_suppkey_x)]['l_orderkey_y']

In [16]:
print(f"inner_cond: {len(inner_cond)}")
inner_cond

inner_cond: 190928

0           10149
2           10149
3           10149
4           10149
6           30374
           ...
266806    5917315
266807    5920835
266808    5920835
266811    5958692
266812    5958692
Name: l_orderkey_y, Length: 190928, dtype: int64

In [17]:
df_join_4 = df_join_3.merge(inner_cond, left_on=['l_orderkey_x'], right_on=['l_orderkey_y'], how='outer', sort=False, indicator=True)
df_join_4 = df_join_4[df_join_4._merge == 'left_only'].drop('_merge', axis = 1)
df_scan_6 = lineitem[['l_orderkey', 'l_suppkey']]
inner_cond = df_join_4.merge(df_scan_6, left_on='l_orderkey_x', right_on='l_orderkey', how='inner', sort=False)
inner_cond = inner_cond[(inner_cond.l_suppkey != inner_cond.l_suppkey_x)]
df_join_5 = df_join_4[df_join_4['l_orderkey_x'].isin(inner_cond['l_orderkey'])]
df_group_1 = df_join_5 \
    .groupby(['s_name'], sort=False, as_index=False) \
    .agg(
        count=('l_receiptdate', 'count'),
    )
df_sort_1 = df_group_1.sort_values(
    by=['count', 's_name'],
    ascending=[False, True]
)
#df_limit_1 = df_sort_1.head(100)
df_output_1 = df_sort_1.rename(columns={'count': 'numwait'})
df_output_1 = df_output_1[['s_name', 'numwait']]

In [18]:
df_output_1

                 s_name  numwait
121  Supplier#000002829       20
231  Supplier#000005808       18
5    Supplier#000000262       17
17   Supplier#000000496       17
96   Supplier#000002160       17
..                  ...      ...
238  Supplier#000005998        4
398  Supplier#000009721        4
272  Supplier#000006684        3
323  Supplier#000007656        3
340  Supplier#000008136        3

[411 rows x 2 columns]

In [19]:
import json
sdqlpy_data = None
with open("../../SDQL/hesam_meeting/data_q21_new.json") as f:
    sdqlpy_data = json.load(f)

In [22]:
len(df_output_1['s_name'])

411

In [21]:
sdqlpy_results = sdqlpy_data['Result']
len(sdqlpy_results['s_name'])

411

In [29]:
from collections import Counter

pd_names = list(df_output_1['s_name'].to_list())
sdql_names = list(sdqlpy_results['s_name'])

Counter(pd_names) == Counter(sdql_names)

True

In [34]:
pd_numwait = list(df_output_1['numwait'].to_list())
sdql_numwait = [int(x) for x in list(sdqlpy_results['numwait'])]

Counter(pd_numwait) == Counter(sdql_numwait)

True

In [36]:
# Iterate through Pandas
for idx, pd_name in enumerate(pd_names):
    # Find index in SDQLpy
    pos = sdql_names.index(pd_name)
    assert pd_numwait[idx] == int(sdql_numwait[pos])
    
# Iterate through SDQLpy
for idx, sdql_name in enumerate(sdql_names):
    # Find index in Pandas
    pos = pd_names.index(sdql_name)
    assert int(sdql_numwait[idx]) == pd_numwait[pos]

In [37]:
hesam_results = "<Supplier#000000889,13> -> true, <Supplier#000000472,11> -> true, <Supplier#000006598,8> -> true, <Supplier#000008996,5> -> true, <Supplier#000003374,8> -> true, <Supplier#000003014,8> -> true, <Supplier#000003414,8> -> true, <Supplier#000005304,8> -> true, <Supplier#000000460,8> -> true, <Supplier#000001120,8> -> true, <Supplier#000002256,8> -> true, <Supplier#000007494,8> -> true, <Supplier#000000825,11> -> true, <Supplier#000002647,12> -> true, <Supplier#000002483,12> -> true, <Supplier#000006505,12> -> true, <Supplier#000003645,12> -> true, <Supplier#000006767,12> -> true, <Supplier#000005643,6> -> true, <Supplier#000004625,6> -> true, <Supplier#000005347,6> -> true, <Supplier#000001665,6> -> true, <Supplier#000000687,6> -> true, <Supplier#000008669,6> -> true, <Supplier#000004169,6> -> true, <Supplier#000004303,6> -> true, <Supplier#000003063,17> -> true, <Supplier#000009543,6> -> true, <Supplier#000008529,6> -> true, <Supplier#000001347,6> -> true, <Supplier#000009561,6> -> true, <Supplier#000002301,17> -> true, <Supplier#000007371,6> -> true, <Supplier#000006453,5> -> true, <Supplier#000009850,11> -> true, <Supplier#000009898,11> -> true, <Supplier#000001916,12> -> true, <Supplier#000008876,12> -> true, <Supplier#000002717,5> -> true, <Supplier#000008492,12> -> true, <Supplier#000008490,12> -> true, <Supplier#000008396,12> -> true, <Supplier#000001896,6> -> true, <Supplier#000001152,11> -> true, <Supplier#000008354,11> -> true, <Supplier#000003735,12> -> true, <Supplier#000002357,12> -> true, <Supplier#000002039,12> -> true, <Supplier#000003519,12> -> true, <Supplier#000006756,7> -> true, <Supplier#000007312,7> -> true, <Supplier#000003048,13> -> true, <Supplier#000007602,13> -> true, <Supplier#000006326,13> -> true, <Supplier#000006624,13> -> true, <Supplier#000002926,12> -> true, <Supplier#000007579,14> -> true, <Supplier#000005920,10> -> true, <Supplier#000008908,10> -> true, <Supplier#000007523,8> -> true, <Supplier#000006378,9> -> true, <Supplier#000002370,9> -> true, <Supplier#000007370,9> -> true, <Supplier#000006381,8> -> true, <Supplier#000004489,14> -> true, <Supplier#000006384,13> -> true, <Supplier#000000648,9> -> true, <Supplier#000005244,9> -> true, <Supplier#000004786,9> -> true, <Supplier#000001724,9> -> true, <Supplier#000001122,9> -> true, <Supplier#000005583,14> -> true, <Supplier#000002344,13> -> true, <Supplier#000009648,9> -> true, <Supplier#000005568,9> -> true, <Supplier#000004100,7> -> true, <Supplier#000002846,11> -> true, <Supplier#000006705,8> -> true, <Supplier#000006682,13> -> true, <Supplier#000009164,9> -> true, <Supplier#000000188,9> -> true, <Supplier#000006394,13> -> true, <Supplier#000003234,13> -> true, <Supplier#000002596,13> -> true, <Supplier#000009804,5> -> true, <Supplier#000001944,5> -> true, <Supplier#000000602,9> -> true, <Supplier#000005004,9> -> true, <Supplier#000002796,9> -> true, <Supplier#000002312,13> -> true, <Supplier#000002095,16> -> true, <Supplier#000009727,16> -> true, <Supplier#000001390,11> -> true, <Supplier#000006757,12> -> true, <Supplier#000006253,12> -> true, <Supplier#000002452,7> -> true, <Supplier#000007296,7> -> true, <Supplier#000007116,7> -> true, <Supplier#000007517,12> -> true, <Supplier#000000708,7> -> true, <Supplier#000002056,13> -> true, <Supplier#000000114,11> -> true, <Supplier#000008398,11> -> true, <Supplier#000006569,7> -> true, <Supplier#000002990,8> -> true, <Supplier#000006281,7> -> true, <Supplier#000006210,9> -> true, <Supplier#000008900,12> -> true, <Supplier#000004321,5> -> true, <Supplier#000005848,12> -> true, <Supplier#000008527,5> -> true, <Supplier#000004840,11> -> true, <Supplier#000000846,11> -> true, <Supplier#000007915,6> -> true, <Supplier#000006283,9> -> true, <Supplier#000007381,9> -> true, <Supplier#000002025,9> -> true, <Supplier#000002269,9> -> true, <Supplier#000007127,9> -> true, <Supplier#000003583,9> -> true, <Supplier#000003283,9> -> true, <Supplier#000008376,8> -> true, <Supplier#000005316,8> -> true, <Supplier#000002540,17> -> true, <Supplier#000002160,17> -> true, <Supplier#000001452,8> -> true, <Supplier#000008030,8> -> true, <Supplier#000000718,8> -> true, <Supplier#000005194,8> -> true, <Supplier#000001534,8> -> true, <Supplier#000001439,6> -> true, <Supplier#000001595,6> -> true, <Supplier#000009141,12> -> true, <Supplier#000008283,12> -> true, <Supplier#000000399,5> -> true, <Supplier#000001353,5> -> true, <Supplier#000006027,15> -> true, <Supplier#000002917,12> -> true, <Supplier#000008882,8> -> true, <Supplier#000004888,8> -> true, <Supplier#000002490,14> -> true, <Supplier#000002993,14> -> true, <Supplier#000008180,14> -> true, <Supplier#000009224,14> -> true, <Supplier#000006996,9> -> true, <Supplier#000000929,6> -> true, <Supplier#000000673,12> -> true, <Supplier#000000379,12> -> true, <Supplier#000001456,7> -> true, <Supplier#000009630,7> -> true, <Supplier#000001058,7> -> true, <Supplier#000005997,6> -> true, <Supplier#000009758,7> -> true, <Supplier#000000578,7> -> true, <Supplier#000001062,13> -> true, <Supplier#000006617,8> -> true, <Supplier#000007601,10> -> true, <Supplier#000007491,8> -> true, <Supplier#000005435,14> -> true, <Supplier#000003267,10> -> true, <Supplier#000000427,8> -> true, <Supplier#000001007,8> -> true, <Supplier#000002978,13> -> true, <Supplier#000008718,9> -> true, <Supplier#000009643,8> -> true, <Supplier#000004285,8> -> true, <Supplier#000009647,8> -> true, <Supplier#000000788,13> -> true, <Supplier#000009564,13> -> true, <Supplier#000009200,16> -> true, <Supplier#000004109,8> -> true, <Supplier#000007061,10> -> true, <Supplier#000005721,8> -> true, <Supplier#000001337,12> -> true, <Supplier#000008739,12> -> true, <Supplier#000004274,9> -> true, <Supplier#000000778,9> -> true, <Supplier#000008754,9> -> true, <Supplier#000008210,7> -> true, <Supplier#000009190,9> -> true, <Supplier#000007847,5> -> true, <Supplier#000003777,8> -> true, <Supplier#000001498,13> -> true, <Supplier#000008234,13> -> true, <Supplier#000000811,12> -> true, <Supplier#000004472,13> -> true, <Supplier#000005236,13> -> true, <Supplier#000000436,13> -> true, <Supplier#000006611,10> -> true, <Supplier#000006259,10> -> true, <Supplier#000009436,13> -> true, <Supplier#000000610,13> -> true, <Supplier#000008134,13> -> true, <Supplier#000006128,6> -> true, <Supplier#000000920,9> -> true, <Supplier#000006939,16> -> true, <Supplier#000004831,12> -> true, <Supplier#000006693,10> -> true, <Supplier#000000144,4> -> true, <Supplier#000000918,9> -> true, <Supplier#000004994,9> -> true, <Supplier#000005896,9> -> true, <Supplier#000006241,13> -> true, <Supplier#000006537,7> -> true, <Supplier#000003727,13> -> true, <Supplier#000006629,13> -> true, <Supplier#000007021,13> -> true, <Supplier#000001789,7> -> true, <Supplier#000004163,7> -> true, <Supplier#000007889,12> -> true, <Supplier#000006909,12> -> true, <Supplier#000003834,4> -> true, <Supplier#000008695,14> -> true, <Supplier#000000633,14> -> true, <Supplier#000008094,9> -> true, <Supplier#000006547,11> -> true, <Supplier#000003517,9> -> true, <Supplier#000007619,9> -> true, <Supplier#000007387,11> -> true, <Supplier#000006667,11> -> true, <Supplier#000007261,11> -> true, <Supplier#000000445,9> -> true, <Supplier#000005469,9> -> true, <Supplier#000000503,9> -> true, <Supplier#000005061,9> -> true, <Supplier#000001601,9> -> true, <Supplier#000008105,9> -> true, <Supplier#000005685,9> -> true, <Supplier#000008147,9> -> true, <Supplier#000007382,15> -> true, <Supplier#000000262,17> -> true, <Supplier#000008301,9> -> true, <Supplier#000002707,11> -> true, <Supplier#000003675,9> -> true, <Supplier#000007511,9> -> true, <Supplier#000009896,13> -> true, <Supplier#000002615,13> -> true, <Supplier#000007497,13> -> true, <Supplier#000006737,13> -> true, <Supplier#000007417,13> -> true, <Supplier#000006013,9> -> true, <Supplier#000005799,16> -> true, <Supplier#000005808,18> -> true, <Supplier#000003806,13> -> true, <Supplier#000003075,15> -> true, <Supplier#000003335,15> -> true, <Supplier#000007131,15> -> true, <Supplier#000007255,11> -> true, <Supplier#000006795,15> -> true, <Supplier#000009787,15> -> true, <Supplier#000001161,15> -> true, <Supplier#000005649,15> -> true, <Supplier#000000565,15> -> true, <Supplier#000001047,15> -> true, <Supplier#000006379,8> -> true, <Supplier#000007142,10> -> true, <Supplier#000006497,7> -> true, <Supplier#000008331,17> -> true, <Supplier#000005774,14> -> true, <Supplier#000006450,16> -> true, <Supplier#000000821,12> -> true, <Supplier#000001925,12> -> true, <Supplier#000005998,4> -> true, <Supplier#000006684,3> -> true, <Supplier#000000709,10> -> true, <Supplier#000005613,8> -> true, <Supplier#000001251,8> -> true, <Supplier#000004539,8> -> true, <Supplier#000005755,8> -> true, <Supplier#000005193,8> -> true, <Supplier#000005383,10> -> true, <Supplier#000004009,10> -> true, <Supplier#000000669,10> -> true, <Supplier#000005627,10> -> true, <Supplier#000001960,14> -> true, <Supplier#000000167,10> -> true, <Supplier#000005413,8> -> true, <Supplier#000000415,8> -> true, <Supplier#000008333,8> -> true, <Supplier#000003212,10> -> true, <Supplier#000005906,13> -> true, <Supplier#000006925,7> -> true, <Supplier#000006967,7> -> true, <Supplier#000007656,3> -> true, <Supplier#000006999,7> -> true, <Supplier#000005235,10> -> true, <Supplier#000005277,10> -> true, <Supplier#000008713,10> -> true, <Supplier#000001053,10> -> true, <Supplier#000003646,11> -> true, <Supplier#000007662,12> -> true, <Supplier#000006596,5> -> true, <Supplier#000006342,11> -> true, <Supplier#000007686,12> -> true, <Supplier#000003266,12> -> true, <Supplier#000003949,9> -> true, <Supplier#000002949,9> -> true, <Supplier#000009268,6> -> true, <Supplier#000009053,7> -> true, <Supplier#000009217,7> -> true, <Supplier#000005319,7> -> true, <Supplier#000001511,7> -> true, <Supplier#000009337,7> -> true, <Supplier#000002684,11> -> true, <Supplier#000005842,16> -> true, <Supplier#000003262,11> -> true, <Supplier#000001393,7> -> true, <Supplier#000004199,10> -> true, <Supplier#000002829,20> -> true, <Supplier#000009855,8> -> true, <Supplier#000005619,7> -> true, <Supplier#000002915,9> -> true, <Supplier#000004501,11> -> true, <Supplier#000008551,9> -> true, <Supplier#000008671,9> -> true, <Supplier#000001019,9> -> true, <Supplier#000008627,11> -> true, <Supplier#000001083,11> -> true, <Supplier#000003294,12> -> true, <Supplier#000009179,9> -> true, <Supplier#000008055,9> -> true, <Supplier#000000496,17> -> true, <Supplier#000003372,11> -> true, <Supplier#000007290,11> -> true, <Supplier#000007532,11> -> true, <Supplier#000001046,15> -> true, <Supplier#000000486,15> -> true, <Supplier#000002410,11> -> true, <Supplier#000004873,10> -> true, <Supplier#000001907,7> -> true, <Supplier#000003618,11> -> true, <Supplier#000005178,17> -> true, <Supplier#000007228,8> -> true, <Supplier#000007002,8> -> true, <Supplier#000003220,8> -> true, <Supplier#000000357,13> -> true, <Supplier#000004793,10> -> true, <Supplier#000002891,11> -> true, <Supplier#000009435,13> -> true, <Supplier#000007054,12> -> true, <Supplier#000009861,9> -> true, <Supplier#000001435,15> -> true, <Supplier#000001809,9> -> true, <Supplier#000003205,6> -> true, <Supplier#000007909,10> -> true, <Supplier#000004829,9> -> true, <Supplier#000009721,4> -> true, <Supplier#000009891,9> -> true, <Supplier#000000659,11> -> true, <Supplier#000005697,11> -> true, <Supplier#000001615,11> -> true, <Supplier#000009815,9> -> true, <Supplier#000005720,10> -> true, <Supplier#000000500,10> -> true, <Supplier#000008951,9> -> true, <Supplier#000001951,9> -> true, <Supplier#000009137,11> -> true, <Supplier#000004477,7> -> true, <Supplier#000002322,7> -> true, <Supplier#000003548,7> -> true, <Supplier#000008913,15> -> true, <Supplier#000008811,11> -> true, <Supplier#000007880,6> -> true, <Supplier#000000660,5> -> true, <Supplier#000009835,11> -> true, <Supplier#000000977,11> -> true, <Supplier#000000074,10> -> true, <Supplier#000001054,10> -> true, <Supplier#000005578,10> -> true, <Supplier#000002814,6> -> true, <Supplier#000003168,9> -> true, <Supplier#000002323,14> -> true, <Supplier#000003101,14> -> true, <Supplier#000006825,13> -> true, <Supplier#000007626,9> -> true, <Supplier#000003248,9> -> true, <Supplier#000007668,9> -> true, <Supplier#000002546,9> -> true, <Supplier#000001572,10> -> true, <Supplier#000001274,10> -> true, <Supplier#000008394,10> -> true, <Supplier#000008136,3> -> true, <Supplier#000004925,10> -> true, <Supplier#000001356,10> -> true, <Supplier#000002869,11> -> true, <Supplier#000005390,6> -> true, <Supplier#000000762,12> -> true, <Supplier#000008702,12> -> true, <Supplier#000000670,6> -> true, <Supplier#000000380,11> -> true, <Supplier#000005042,11> -> true, <Supplier#000005662,11> -> true, <Supplier#000002005,16> -> true, <Supplier#000006800,15> -> true, <Supplier#000006824,15> -> true, <Supplier#000007810,12> -> true, <Supplier#000007896,12> -> true, <Supplier#000006892,11> -> true, <Supplier#000007950,11> -> true, <Supplier#000003992,11> -> true, <Supplier#000006087,5> -> true, <Supplier#000002225,5> -> true, <Supplier#000003521,5> -> true, <Supplier#000007441,5> -> true, <Supplier#000006561,5> -> true, <Supplier#000005436,12> -> true, <Supplier#000001336,15> -> true, <Supplier#000008390,12> -> true, <Supplier#000004112,12> -> true, <Supplier#000005376,11> -> true, <Supplier#000008310,11> -> true"

In [48]:
h_names = []
h_numwait = []
for x in hesam_results.split("-> true,"):
    name, numwait = (x.strip()[1:-1].split(",")[:2])
    numwait = numwait.split(">")[0]
    h_names.append(str(name))
    h_numwait.append(int(numwait))

In [50]:
print(Counter(pd_names) == Counter(h_names))
print(Counter(pd_numwait) == Counter(h_numwait))

# Iterate through Pandas
for idx, pd_name in enumerate(pd_names):
    # Find index in Hesam
    pos = h_names.index(pd_name)
    assert pd_numwait[idx] == int(h_numwait[pos])
    
# Iterate through Hesam
for idx, h_name in enumerate(h_names):
    # Find index in Pandas
    pos = pd_names.index(h_name)
    assert int(h_numwait[idx]) == pd_numwait[pos]

True
True