In [3]:
from numpy import char
from datetime import date
import pandas as pd
import numpy as np
import time
pd.set_option('display.float_format', str)

In [4]:
import pandas as pd


# Lineitem

l_columnnames = ["L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX",
                "L_RETURNFLAG", "L_LINESTATUS", "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"]

for i in range(len(l_columnnames)):
    l_columnnames[i] = l_columnnames[i].lower()

l_data_types = {
    'l_orderkey': int,
    'l_partkey': int,
    'l_suppkey': int,
    'l_linenumber': int,
    'l_quantity': float,
    'l_extendedprice': float,
    'l_discount': float,
    'l_tax': float,
    'l_returnflag': str,
    'l_linestatus': str,
    'l_shipinstruct': str,
    'l_shipmode': str,
    'l_comment': str
}

l_parse_dates = ['l_shipdate', 'l_commitdate', 'l_receiptdate']

# Don't set indexes, as we can't access them with Pandas selection!
lineitem = pd.read_table("../data_storage/lineitem.tbl.csv", sep="|", names=l_columnnames, dtype=l_data_types, parse_dates=l_parse_dates)

# Order

o_columnnames = ["O_ORDERKEY", "O_CUSTKEY", "O_ORDERSTATUS", "O_TOTALPRICE", "O_ORDERDATE", "O_ORDERPRIORITY", "O_CLERK", "O_SHIPPRIORITY", "O_COMMENT"]

for i in range(len(o_columnnames)):
    o_columnnames[i] = o_columnnames[i].lower()
    
o_data_types = {
    'o_orderkey': int,
    'o_custkey': int,
    'o_orderstatus': str,
    'o_totalprice': float,
    'o_orderpriority': str,
    'o_clerk': str,
    'o_shippriority': int,
    'o_comment': str
}

o_parse_dates = ['o_orderdate']

# Don't set indexes, as we can't access them with Pandas selection!
orders = pd.read_table("../data_storage/orders.tbl.csv", sep="|", names=o_columnnames, dtype=o_data_types, parse_dates=o_parse_dates)

# Customer

c_columnnames = ["C_CUSTKEY", "C_NAME", "C_ADDRESS", "C_NATIONKEY", "C_PHONE", "C_ACCTBAL", "C_MKTSEGMENT", "C_COMMENT"]

for i in range(len(c_columnnames)):
    c_columnnames[i] = c_columnnames[i].lower()
    
c_data_types = {
    'c_custkey': int,
    'c_name': str,
    'c_address': str,
    'c_nationkey': int,
    'c_phone': str,
    'c_acctbal': float,
    'c_mktsegment': str,
    'c_comment': str
}

c_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
customer = pd.read_table("../data_storage/customer.tbl.csv", sep="|", names=c_columnnames, dtype=c_data_types, parse_dates=c_parse_dates)

# Part

p_columnnames = ["P_PARTKEY", "P_NAME", "P_MFGR", "P_BRAND", "P_TYPE", "P_SIZE", "P_CONTAINER", "P_RETAILPRICE", "P_COMMENT"]

for i in range(len(p_columnnames)):
    p_columnnames[i] = p_columnnames[i].lower()
    
p_data_types = {
    'p_partkey': int, 
    'p_name': str,
    'p_mfgr': str,
    'p_brand': str,
    'p_type': str,
    'p_size': int,
    'p_container': str,
    'p_retailprice': float,
    'p_comment': str
}

p_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
part = pd.read_table("../data_storage/part.tbl.csv", sep="|", names=p_columnnames, dtype=p_data_types, parse_dates=p_parse_dates)

# Nation

n_columnnames = ["N_NATIONKEY", "N_NAME", "N_REGIONKEY", "N_COMMENT"]

for i in range(len(n_columnnames)):
    n_columnnames[i] = n_columnnames[i].lower()
    
n_data_types = {
    'n_nationkey': int,
    'n_name': str,
    'n_regionkey': int,
    'n_comment': str,
}

n_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
nation = pd.read_table("../data_storage/nation.tbl.csv", sep="|", names=n_columnnames, dtype=n_data_types, parse_dates=n_parse_dates)

# Supplier

s_columnnames = ["S_SUPPKEY", "S_NAME", "S_ADDRESS", "S_NATIONKEY", "S_PHONE", "S_ACCTBAL", "S_COMMENT"]

for i in range(len(s_columnnames)):
    s_columnnames[i] = s_columnnames[i].lower()

s_data_types = {
    's_suppkey': int,
    's_name': str,
    's_address': str,
    's_nationkey': int,
    's_phone': str,
    's_acctbal': float,
    's_comment': str
}

s_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
# Don't set indexes, as we can't access them with Pandas selection!
supplier = pd.read_table("../data_storage/supplier.tbl.csv", sep="|", names=s_columnnames, dtype=s_data_types, parse_dates=s_parse_dates)

# Partsupp

ps_columnnames = ["PS_PARTKEY", "PS_SUPPKEY", "PS_AVAILQTY", "PS_SUPPLYCOST", "PS_COMMENT"]

for i in range(len(ps_columnnames)):
    ps_columnnames[i] = ps_columnnames[i].lower()

ps_data_types = {
    'ps_partkey': int,
    'ps_suppkey': int,
    'ps_availqty': int,
    'ps_supplycost': float,
    'ps_comment': str
}

ps_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
partsupp = pd.read_table("../data_storage/partsupp.tbl.csv", sep="|", names=ps_columnnames, dtype=ps_data_types, parse_dates=ps_parse_dates)

# Region

r_columnnames = ["R_REGIONKEY", "R_NAME", "R_COMMENT"]

for i in range(len(r_columnnames)):
    r_columnnames[i] = r_columnnames[i].lower()

r_data_types = {
    'r_regionkey': int,
    'r_name': str,
    'r_comment': str
}

r_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
region = pd.read_table("../data_storage/region.tbl.csv", sep="|", names=r_columnnames, dtype=r_data_types, parse_dates=r_parse_dates)

In [5]:
df_filter_1 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_supplycost']]
df_filter_2 = supplier[['s_suppkey', 's_nationkey', 's_acctbal', 's_name', 's_address', 's_phone', 's_comment']]
df_merge_1 = df_filter_1.merge(df_filter_2, left_on=['ps_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_3 = nation[['n_nationkey', 'n_regionkey', 'n_name']]
df_filter_4 = region[(region.r_name == 'EUROPE') & (~region.r_name.isnull())]
df_filter_4 = df_filter_4[['r_regionkey', 'r_name']]
df_merge_2 = df_filter_3.merge(df_filter_4, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_merge_3 = df_merge_1.merge(df_merge_2, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_filter_5 = part[(part.p_size == 15) & (~part.p_size.isnull()) & (part.p_type.str.contains("^.*?BRASS$",regex=True))]
df_filter_5 = df_filter_5[['p_partkey', 'p_size', 'p_type', 'p_mfgr']]
df_merge_4 = df_merge_3.merge(df_filter_5, left_on=['ps_partkey'], right_on=['p_partkey'], how="inner", sort=False)
df_filter_6 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_supplycost']]
df_filter_7 = supplier[['s_suppkey', 's_nationkey']]
df_merge_5 = df_filter_6.merge(df_filter_7, left_on=['ps_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_8 = nation[['n_nationkey', 'n_regionkey']]
df_merge_6 = df_merge_5.merge(df_filter_8, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_filter_9 = region[(region.r_name == 'EUROPE') & (~region.r_name.isnull())]
df_filter_9 = df_filter_9[['r_regionkey', 'r_name']]
df_merge_7 = df_merge_6.merge(df_filter_9, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_group_1 = df_merge_7 \
    .groupby(['ps_partkey'], sort=False) \
    .agg(
        min_ps_supplycost=("ps_supplycost", "min"),
    )
df_group_1['minps_supplycost'] = df_group_1.min_ps_supplycost
df_group_1 = df_group_1[['minps_supplycost']]
df_group_1 = df_group_1.reset_index(level=0)
df_merge_8 = df_merge_4.merge(df_group_1, left_on=['p_partkey'], right_on=['ps_partkey'], how="inner", sort=False)
df_merge_8 = df_merge_8[(df_merge_8.ps_supplycost == df_merge_8.minps_supplycost)]
df_aggr_1 = pd.DataFrame()
df_aggr_1['s_acctbal'] = (df_merge_8.s_acctbal)
df_aggr_1['s_name'] = (df_merge_8.s_name)
df_aggr_1['n_name'] = (df_merge_8.n_name)
df_aggr_1['p_partkey'] = (df_merge_8.p_partkey)
df_aggr_1['p_mfgr'] = (df_merge_8.p_mfgr)
df_aggr_1['s_address'] = (df_merge_8.s_address)
df_aggr_1['s_phone'] = (df_merge_8.s_phone)
df_aggr_1['s_comment'] = (df_merge_8.s_comment)
df_aggr_1 = df_aggr_1[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
df_sort_1 = df_aggr_1.sort_values(by=['s_acctbal', 'n_name', 's_name', 'p_partkey'], ascending=[False, True, True, True])
df_limit_1 = df_sort_1.head(100)
#return df_limit_1

In [6]:
df_limit_1

,s_acctbal,s_name,n_name,p_partkey,p_mfgr,s_address,s_phone,s_comment
385,9938.53,Supplier#000005359,UNITED KINGDOM,185358,Manufacturer#4,"QKuHYh,vZGiwu2FWEJoLDx04",33-429-790-6131,uriously regular requests hag
257,9937.84,Supplier#000005969,ROMANIA,108438,Manufacturer#1,"ANDENSOSmk,miq23Xfb5RWt6dvUcvt6Qa",29-520-692-3537,efully express instructions. regular requests ...
380,9936.22,Supplier#000005250,UNITED KINGDOM,249,Manufacturer#4,B3rqp0xbSEim4Mpy2RH J,33-320-228-2957,etect about the furiously final accounts. slyl...
638,9923.77,Supplier#000002324,GERMANY,29821,Manufacturer#4,y3OD9UywSTOk,17-779-299-1839,ackages boost blithely. blithely regular depos...
613,9871.22,Supplier#000006373,GERMANY,43868,Manufacturer#5,J8fcXWsTqM,17-813-485-8637,etect blithely bold asymptotes. fluffily ironi...
...,...,...,...,...,...,...,...,...
636,7887.08,Supplier#000009792,GERMANY,164759,Manufacturer#3,Y28ITVeYriT3kIGdV2K8fSZ V2UqT5H1Otz,17-988-938-4296,ckly around the carefully fluffy theodolites. ...
166,7871.5,Supplier#000007206,RUSSIA,104695,Manufacturer#1,3w fNCnrVmvJjE95sgWZzvW,32-432-452-7731,ironic requests. furiously final theodolites c...
56,7852.45,Supplier#000005864,RUSSIA,8363,Manufacturer#4,"WCNfBPZeSXh3h,c",32-454-883-3821,usly unusual pinto beans. brave ideas sleep ca...
111,7850.66,Supplier#000001518,UNITED KINGDOM,86501,Manufacturer#1,ONda3YJiHKJOC,33-730-383-3892,ifts haggle fluffily pending pai
555,7843.52,Supplier#000006683,FRANCE,11680,Manufacturer#4,2Z0JGkiv01Y00oCFwUGfviIbhzCdy,16-464-517-8943,"express, final pinto beans x-ray slyly asympt..."

In [7]:
df_filter_1 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_supplycost']]
df_filter_2 = supplier[['s_suppkey', 's_nationkey', 's_acctbal', 's_name', 's_address', 's_phone', 's_comment']]
df_merge_1 = df_filter_1.merge(df_filter_2, left_on=['ps_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_3 = nation[['n_nationkey', 'n_regionkey', 'n_name']]
df_filter_4 = region[(region.r_name == 'EUROPE') & (~region.r_name.isnull())]
df_filter_4 = df_filter_4[['r_regionkey', 'r_name']]
df_merge_2 = df_filter_3.merge(df_filter_4, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_merge_3 = df_merge_1.merge(df_merge_2, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_filter_5 = part[(part.p_size == 15) & (~part.p_size.isnull()) & (part.p_type.str.contains("^.*?BRASS$",regex=True))]
df_filter_5 = df_filter_5[['p_partkey', 'p_size', 'p_type', 'p_mfgr']]
df_merge_4 = df_merge_3.merge(df_filter_5, left_on=['ps_partkey'], right_on=['p_partkey'], how="inner", sort=False)
df_filter_6 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_supplycost']]
df_filter_7 = supplier[['s_suppkey', 's_nationkey']]
df_merge_5 = df_filter_6.merge(df_filter_7, left_on=['ps_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_8 = nation[['n_nationkey', 'n_regionkey']]
df_merge_6 = df_merge_5.merge(df_filter_8, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_filter_9 = region[(region.r_name == 'EUROPE') & (~region.r_name.isnull())]
df_filter_9 = df_filter_9[['r_regionkey', 'r_name']]
df_merge_7 = df_merge_6.merge(df_filter_9, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_group_1 = df_merge_7 \
    .groupby(['ps_partkey'], sort=False) \
    .agg(
        min_ps_supplycost=("ps_supplycost", "min"),
    )
df_group_1['minps_supplycost'] = df_group_1.min_ps_supplycost
df_group_1 = df_group_1[['minps_supplycost']]
df_group_1 = df_group_1.reset_index(level=0)
df_merge_8 = df_merge_4.merge(df_group_1, left_on=['p_partkey'], right_on=['ps_partkey'], how="inner", sort=False)
df_merge_8 = df_merge_8[(df_merge_8.ps_supplycost == df_merge_8.minps_supplycost)]
df_aggr_1 = pd.DataFrame()
df_aggr_1['s_acctbal'] = (df_merge_8.s_acctbal)
df_aggr_1['s_name'] = (df_merge_8.s_name)
df_aggr_1['n_name'] = (df_merge_8.n_name)
df_aggr_1['p_partkey'] = (df_merge_8.p_partkey)
df_aggr_1['p_mfgr'] = (df_merge_8.p_mfgr)
df_aggr_1['s_address'] = (df_merge_8.s_address)
df_aggr_1['s_phone'] = (df_merge_8.s_phone)
df_aggr_1['s_comment'] = (df_merge_8.s_comment)
df_aggr_1 = df_aggr_1[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
df_sort_1 = df_aggr_1.sort_values(by=['s_acctbal', 'n_name', 's_name', 'p_partkey'], ascending=[False, True, True, True])
df_limit_1 = df_sort_1.head(100)
#return df_limit_1

In [8]:
df_limit_1

,s_acctbal,s_name,n_name,p_partkey,p_mfgr,s_address,s_phone,s_comment
385,9938.53,Supplier#000005359,UNITED KINGDOM,185358,Manufacturer#4,"QKuHYh,vZGiwu2FWEJoLDx04",33-429-790-6131,uriously regular requests hag
257,9937.84,Supplier#000005969,ROMANIA,108438,Manufacturer#1,"ANDENSOSmk,miq23Xfb5RWt6dvUcvt6Qa",29-520-692-3537,efully express instructions. regular requests ...
380,9936.22,Supplier#000005250,UNITED KINGDOM,249,Manufacturer#4,B3rqp0xbSEim4Mpy2RH J,33-320-228-2957,etect about the furiously final accounts. slyl...
638,9923.77,Supplier#000002324,GERMANY,29821,Manufacturer#4,y3OD9UywSTOk,17-779-299-1839,ackages boost blithely. blithely regular depos...
613,9871.22,Supplier#000006373,GERMANY,43868,Manufacturer#5,J8fcXWsTqM,17-813-485-8637,etect blithely bold asymptotes. fluffily ironi...
...,...,...,...,...,...,...,...,...
636,7887.08,Supplier#000009792,GERMANY,164759,Manufacturer#3,Y28ITVeYriT3kIGdV2K8fSZ V2UqT5H1Otz,17-988-938-4296,ckly around the carefully fluffy theodolites. ...
166,7871.5,Supplier#000007206,RUSSIA,104695,Manufacturer#1,3w fNCnrVmvJjE95sgWZzvW,32-432-452-7731,ironic requests. furiously final theodolites c...
56,7852.45,Supplier#000005864,RUSSIA,8363,Manufacturer#4,"WCNfBPZeSXh3h,c",32-454-883-3821,usly unusual pinto beans. brave ideas sleep ca...
111,7850.66,Supplier#000001518,UNITED KINGDOM,86501,Manufacturer#1,ONda3YJiHKJOC,33-730-383-3892,ifts haggle fluffily pending pai
555,7843.52,Supplier#000006683,FRANCE,11680,Manufacturer#4,2Z0JGkiv01Y00oCFwUGfviIbhzCdy,16-464-517-8943,"express, final pinto beans x-ray slyly asympt..."

In [9]:
df_filter_1 = part[(part.p_type.str.contains("^.*?BRASS$",regex=True)) & (part.p_size == 15)]
df_filter_1 = df_filter_1[['p_partkey', 'p_mfgr']]
df_filter_2 = partsupp[['ps_partkey', 'ps_suppkey', 'ps_availqty', 'ps_supplycost', 'ps_comment']]
df_filter_3 = supplier[['s_suppkey', 's_name', 's_address', 's_nationkey', 's_phone', 's_acctbal', 's_comment']]
df_filter_4 = nation[['n_nationkey', 'n_name', 'n_regionkey', 'n_comment']]
df_filter_5 = region[(region.r_name == 'EUROPE')]
df_filter_5 = df_filter_5[['r_regionkey']]
df_merge_1 = df_filter_4.merge(df_filter_5, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_merge_1 = df_merge_1[['n_name', 'n_nationkey']]
df_merge_2 = df_filter_3.merge(df_merge_1, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_merge_2 = df_merge_2[['s_acctbal', 's_name', 's_address', 's_phone', 's_comment', 's_suppkey', 'n_name']]
df_merge_3 = df_filter_2.merge(df_merge_2, left_on=['ps_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_merge_3 = df_merge_3[['s_acctbal', 's_name', 's_address', 's_phone', 's_comment', 'ps_partkey', 'ps_supplycost', 'n_name']]
df_merge_4 = df_filter_1.merge(df_merge_3, left_on=['p_partkey'], right_on=['ps_partkey'], how="inner", sort=False)
df_merge_4 = df_merge_4[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment', 'ps_supplycost']]
df_filter_6 = supplier[['s_suppkey', 's_name', 's_address', 's_nationkey', 's_phone', 's_acctbal', 's_comment']]
df_filter_7 = partsupp[['ps_supplycost', 'ps_suppkey', 'ps_partkey']]
df_filter_8 = part[['p_partkey']]
df_merge_5 = df_filter_7.merge(df_filter_8, left_on=['ps_partkey'], right_on=['p_partkey'], how="inner", sort=False)
df_merge_5 = df_merge_5[['ps_supplycost', 'ps_suppkey', 'p_partkey']]
df_merge_6 = df_filter_6.merge(df_merge_5, left_on=['s_suppkey'], right_on=['ps_suppkey'], how="inner", sort=False)
df_merge_6 = df_merge_6[['ps_supplycost', 's_nationkey', 'p_partkey']]
df_filter_9 = nation[['n_nationkey', 'n_name', 'n_regionkey', 'n_comment']]
df_filter_10 = region[(region.r_name == 'EUROPE')]
df_filter_10 = df_filter_10[['r_regionkey']]
df_merge_7 = df_filter_9.merge(df_filter_10, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_merge_7 = df_merge_7[['n_nationkey']]
df_merge_8 = df_merge_6.merge(df_merge_7, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_merge_8 = df_merge_8[['ps_supplycost', 'p_partkey']]
df_group_1 = df_merge_8 \
    .groupby(['p_partkey'], sort=False, as_index=False) \
    .agg(
        min_ps_supplycost=("ps_supplycost", "min"),
    )
df_group_1['minps_supplycost'] = df_group_1.min_ps_supplycost
df_group_1 = df_group_1[['minps_supplycost', 'p_partkey']]
df_merge_9 = df_merge_4.merge(df_group_1, left_on=['ps_supplycost', 'p_partkey'], right_on=['minps_supplycost', 'p_partkey'], how="inner", sort=False)
df_merge_9 = df_merge_9[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
df_sort_1 = df_merge_9.sort_values(by=['s_acctbal', 'n_name', 's_name', 'p_partkey'], ascending=[False, True, True, True])
df_sort_1 = df_sort_1[['s_acctbal', 's_name', 'n_name', 'p_partkey', 'p_mfgr', 's_address', 's_phone', 's_comment']]
df_limit_1 = df_sort_1.head(100)

In [10]:
df_limit_1

,s_acctbal,s_name,n_name,p_partkey,p_mfgr,s_address,s_phone,s_comment
427,9938.53,Supplier#000005359,UNITED KINGDOM,185358,Manufacturer#4,"QKuHYh,vZGiwu2FWEJoLDx04",33-429-790-6131,uriously regular requests hag
256,9937.84,Supplier#000005969,ROMANIA,108438,Manufacturer#1,"ANDENSOSmk,miq23Xfb5RWt6dvUcvt6Qa",29-520-692-3537,efully express instructions. regular requests ...
0,9936.22,Supplier#000005250,UNITED KINGDOM,249,Manufacturer#4,B3rqp0xbSEim4Mpy2RH J,33-320-228-2957,etect about the furiously final accounts. slyl...
77,9923.77,Supplier#000002324,GERMANY,29821,Manufacturer#4,y3OD9UywSTOk,17-779-299-1839,ackages boost blithely. blithely regular depos...
113,9871.22,Supplier#000006373,GERMANY,43868,Manufacturer#5,J8fcXWsTqM,17-813-485-8637,etect blithely bold asymptotes. fluffily ironi...
...,...,...,...,...,...,...,...,...
381,7887.08,Supplier#000009792,GERMANY,164759,Manufacturer#3,Y28ITVeYriT3kIGdV2K8fSZ V2UqT5H1Otz,17-988-938-4296,ckly around the carefully fluffy theodolites. ...
248,7871.5,Supplier#000007206,RUSSIA,104695,Manufacturer#1,3w fNCnrVmvJjE95sgWZzvW,32-432-452-7731,ironic requests. furiously final theodolites c...
22,7852.45,Supplier#000005864,RUSSIA,8363,Manufacturer#4,"WCNfBPZeSXh3h,c",32-454-883-3821,usly unusual pinto beans. brave ideas sleep ca...
204,7850.66,Supplier#000001518,UNITED KINGDOM,86501,Manufacturer#1,ONda3YJiHKJOC,33-730-383-3892,ifts haggle fluffily pending pai
30,7843.52,Supplier#000006683,FRANCE,11680,Manufacturer#4,2Z0JGkiv01Y00oCFwUGfviIbhzCdy,16-464-517-8943,"express, final pinto beans x-ray slyly asympt..."