In [1]:
from numpy import char
from datetime import date
import pandas as pd
import numpy as np
pd.set_option('display.float_format', str)
import time

In [2]:
# Lineitem

l_columnnames = ["L_ORDERKEY", "L_PARTKEY", "L_SUPPKEY", "L_LINENUMBER", "L_QUANTITY", "L_EXTENDEDPRICE", "L_DISCOUNT", "L_TAX",
                "L_RETURNFLAG", "L_LINESTATUS", "L_SHIPDATE", "L_COMMITDATE", "L_RECEIPTDATE", "L_SHIPINSTRUCT", "L_SHIPMODE", "L_COMMENT"]

for i in range(len(l_columnnames)):
    l_columnnames[i] = l_columnnames[i].lower()

l_data_types = {
    'l_orderkey': int,
    'l_partkey': int,
    'l_suppkey': int,
    'l_linenumber': int,
    'l_quantity': float,
    'l_extendedprice': float,
    'l_discount': float,
    'l_tax': float,
    'l_returnflag': str,
    'l_linestatus': str,
    'l_shipinstruct': str,
    'l_shipmode': str,
    'l_comment': str
}

l_parse_dates = ['l_shipdate', 'l_commitdate', 'l_receiptdate']

# Don't set indexes, as we can't access them with Pandas selection!
lineitem = pd.read_table("../data_storage/lineitem.tbl.csv", sep="|", names=l_columnnames, dtype=l_data_types, parse_dates=l_parse_dates)

# Order

o_columnnames = ["O_ORDERKEY", "O_CUSTKEY", "O_ORDERSTATUS", "O_TOTALPRICE", "O_ORDERDATE", "O_ORDERPRIORITY", "O_CLERK", "O_SHIPPRIORITY", "O_COMMENT"]

for i in range(len(o_columnnames)):
    o_columnnames[i] = o_columnnames[i].lower()
    
o_data_types = {
    'o_orderkey': int,
    'o_custkey': int,
    'o_orderstatus': str,
    'o_totalprice': float,
    'o_orderpriority': str,
    'o_clerk': str,
    'o_shippriority': int,
    'o_comment': str
}

o_parse_dates = ['o_orderdate']

# Don't set indexes, as we can't access them with Pandas selection!
orders = pd.read_table("../data_storage/orders.tbl.csv", sep="|", names=o_columnnames, dtype=o_data_types, parse_dates=o_parse_dates)

# Customer

c_columnnames = ["C_CUSTKEY", "C_NAME", "C_ADDRESS", "C_NATIONKEY", "C_PHONE", "C_ACCTBAL", "C_MKTSEGMENT", "C_COMMENT"]

for i in range(len(c_columnnames)):
    c_columnnames[i] = c_columnnames[i].lower()
    
c_data_types = {
    'c_custkey': int,
    'c_name': str,
    'c_address': str,
    'c_nationkey': int,
    'c_phone': str,
    'c_acctbal': float,
    'c_mktsegment': str,
    'c_comment': str
}

c_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
customer = pd.read_table("../data_storage/customer.tbl.csv", sep="|", names=c_columnnames, dtype=c_data_types, parse_dates=c_parse_dates)

# Part

p_columnnames = ["P_PARTKEY", "P_NAME", "P_MFGR", "P_BRAND", "P_TYPE", "P_SIZE", "P_CONTAINER", "P_RETAILPRICE", "P_COMMENT"]

for i in range(len(p_columnnames)):
    p_columnnames[i] = p_columnnames[i].lower()
    
p_data_types = {
    'p_partkey': int, 
    'p_name': str,
    'p_mfgr': str,
    'p_brand': str,
    'p_type': str,
    'p_size': int,
    'p_container': str,
    'p_retailprice': float,
    'p_comment': str
}

p_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
part = pd.read_table("../data_storage/part.tbl.csv", sep="|", names=p_columnnames, dtype=p_data_types, parse_dates=p_parse_dates)

# Nation

n_columnnames = ["N_NATIONKEY", "N_NAME", "N_REGIONKEY", "N_COMMENT"]

for i in range(len(n_columnnames)):
    n_columnnames[i] = n_columnnames[i].lower()
    
n_data_types = {
    'n_nationkey': int,
    'n_name': str,
    'n_regionkey': int,
    'n_comment': str,
}

n_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
nation = pd.read_table("../data_storage/nation.tbl.csv", sep="|", names=n_columnnames, dtype=n_data_types, parse_dates=n_parse_dates)

# Supplier

s_columnnames = ["S_SUPPKEY", "S_NAME", "S_ADDRESS", "S_NATIONKEY", "S_PHONE", "S_ACCTBAL", "S_COMMENT"]

for i in range(len(s_columnnames)):
    s_columnnames[i] = s_columnnames[i].lower()

s_data_types = {
    's_suppkey': int,
    's_name': str,
    's_address': str,
    's_nationkey': int,
    's_phone': str,
    's_acctbal': float,
    's_comment': str
}

s_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
supplier = pd.read_table("../data_storage/supplier.tbl.csv", sep="|", names=s_columnnames, dtype=s_data_types, parse_dates=s_parse_dates)

# Partsupp

ps_columnnames = ["PS_PARTKEY", "PS_SUPPKEY", "PS_AVAILQTY", "PS_SUPPLYCOST", "PS_COMMENT"]

for i in range(len(ps_columnnames)):
    ps_columnnames[i] = ps_columnnames[i].lower()

ps_data_types = {
    'ps_partkey': int,
    'ps_suppkey': int,
    'ps_availqty': int,
    'ps_supplycost': float,
    'ps_comment': str
}

ps_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
partsupp = pd.read_table("../data_storage/partsupp.tbl.csv", sep="|", names=ps_columnnames, dtype=ps_data_types, parse_dates=ps_parse_dates)

# Region

r_columnnames = ["R_REGIONKEY", "R_NAME", "R_COMMENT"]

for i in range(len(r_columnnames)):
    r_columnnames[i] = r_columnnames[i].lower()

r_data_types = {
    'r_regionkey': int,
    'r_name': str,
    'r_comment': str
}

r_parse_dates = []

# Don't set indexes, as we can't access them with Pandas selection!
region = pd.read_table("../data_storage/region.tbl.csv", sep="|", names=r_columnnames, dtype=r_data_types, parse_dates=r_parse_dates)

## Q6

In [3]:
# Hyper Pandas
start_time = time.time()

df_scan_1 = supplier[['s_suppkey', 's_name', 's_address', 's_nationkey', 's_phone', 's_acctbal', 's_comment']]
df_scan_2 = region[(region.r_name == 'ASIA')]
df_scan_2 = df_scan_2[['r_regionkey', 'r_name', 'r_comment']]
df_scan_3 = nation[['n_nationkey', 'n_name', 'n_regionkey', 'n_comment']]
df_join_1 = df_scan_2.merge(df_scan_3, left_on=['r_regionkey'], right_on=['n_regionkey'], how='inner', sort=False)
df_scan_4 = customer[['c_custkey', 'c_name', 'c_address', 'c_nationkey', 'c_phone', 'c_acctbal', 'c_mktsegment', 'c_comment']]
df_join_2 = df_join_1.merge(df_scan_4, left_on=['n_nationkey'], right_on=['c_nationkey'], how='inner', sort=False)
df_scan_5 = orders[orders.o_orderdate.between('1994-01-01', '1995-01-01', inclusive='left')]
df_scan_5 = df_scan_5[['o_orderkey', 'o_custkey', 'o_orderstatus', 'o_totalprice', 'o_orderdate', 'o_orderpriority', 'o_clerk', 'o_shippriority', 'o_comment']]
df_join_3 = df_join_2.merge(df_scan_5, left_on=['c_custkey'], right_on=['o_custkey'], how='inner', sort=False)
df_scan_6 = lineitem[['l_orderkey', 'l_partkey', 'l_suppkey', 'l_linenumber', 'l_quantity', 'l_extendedprice', 'l_discount', 'l_tax', 'l_returnflag', 'l_linestatus', 'l_shipdate', 'l_commitdate', 'l_receiptdate', 'l_shipinstruct', 'l_shipmode', 'l_comment']]
df_join_4 = df_join_3.merge(df_scan_6, left_on=['o_orderkey'], right_on=['l_orderkey'], how='inner', sort=False)
df_join_5 = df_scan_1.merge(df_join_4, left_on=['s_nationkey', 's_suppkey'], right_on=['c_nationkey', 'l_suppkey'], how='inner', sort=False)
df_join_5['l_extendedpricel_discount'] = df_join_5.l_extendedprice * (1 - df_join_5.l_discount)
df_group_1 = df_join_5 \
    .groupby(['n_name'], sort=False, as_index=False) \
    .agg(
        l_extendedpricel_discountsum=('l_extendedpricel_discount', 'sum'),
    )
df_sort_1 = df_group_1.sort_values(
    by=['l_extendedpricel_discountsum'],
    ascending=[False]
)
df_output_1 = df_sort_1.rename(columns={'l_extendedpricel_discountsum': 'revenue'})
df_output_1 = df_output_1[['n_name', 'revenue']]

end_time = time.time()
print(df_output_1)

print("--- %s seconds ---" % (end_time - start_time))
# Should be: 
#              revenue
# 0 123141078.22829999
#

      n_name            revenue
2  INDONESIA      55502041.1697
3    VIETNAM      55295086.9967
0      CHINA      53724494.2566
1      INDIA 52035512.000199996
4      JAPAN      45410175.6954
--- 1.762582540512085 seconds ---

In [5]:
df_filter_1 = lineitem[['l_orderkey', 'l_suppkey', 'l_extendedprice', 'l_discount']]
df_filter_2 = supplier[['s_suppkey', 's_nationkey']]
df_filter_3 = nation[['n_nationkey', 'n_regionkey', 'n_name']]
df_filter_4 = region[(region.r_name == 'ASIA') & (~region.r_name.isnull())]
df_filter_4 = df_filter_4[['r_regionkey', 'r_name']]
df_merge_1 = df_filter_3.merge(df_filter_4, left_on=['n_regionkey'], right_on=['r_regionkey'], how="inner", sort=False)
df_merge_2 = df_filter_2.merge(df_merge_1, left_on=['s_nationkey'], right_on=['n_nationkey'], how="inner", sort=False)
df_merge_3 = df_filter_1.merge(df_merge_2, left_on=['l_suppkey'], right_on=['s_suppkey'], how="inner", sort=False)
df_filter_5 = orders[(orders.o_orderdate>='1994-01-01') & (orders.o_orderdate<'1995-01-01') & (~orders.o_orderdate.isnull())]
df_filter_5 = df_filter_5[['o_custkey', 'o_orderkey', 'o_orderdate']]
df_merge_4 = df_merge_3.merge(df_filter_5, left_on=['l_orderkey'], right_on=['o_orderkey'], how="inner", sort=False)
df_filter_6 = customer[['c_custkey', 'c_nationkey']]
df_merge_5 = df_merge_4.merge(df_filter_6, left_on=['n_nationkey', 's_nationkey', 'o_custkey'], right_on=['c_nationkey', 'c_nationkey', 'c_custkey'], how="inner", sort=False)
df_merge_5['before_1'] = ((df_merge_5.l_extendedprice) * (1 - (df_merge_5.l_discount)))
df_group_1 = df_merge_5 \
    .groupby(['n_name'], sort=False, as_index=False) \
    .agg(
        revenue=("before_1", "sum"),
    )
df_group_1 = df_group_1[['revenue', 'n_name']]
df_sort_1 = df_group_1.sort_values(by=['revenue'], ascending=[False])
df_limit_1 = df_sort_1

In [6]:
df_limit_1

             revenue     n_name
2      55502041.1697  INDONESIA
3      55295086.9967    VIETNAM
1      53724494.2566      CHINA
0 52035512.000199996      INDIA
4      45410175.6954      JAPAN